import { supabase } from './supabase.js';

const CORE=[
 {id:'m1',domain:'Math',skill:'Linear Equations',d:1,q:'Solve: 4x + 6 = 30',o:['4','5','6','9'],a:2},
 {id:'m2',domain:'Math',skill:'Percent',d:1,q:'A $120 jacket is discounted 30%. What is the sale price?',o:['$36','$72','$84','$90'],a:2},
 {id:'m3',domain:'Math',skill:'Rates',d:1,q:'A runner covers 7.5 miles in 60 minutes at a constant rate. How far in 36 minutes?',o:['3.5 miles','4.5 miles','5 miles','6 miles'],a:1},
 {id:'m4',domain:'Math',skill:'Ratios',d:2,q:'The ratio of red to blue marbles is 5:3. If there are 48 marbles total, how many are blue?',o:['15','18','24','30'],a:1},
 {id:'m5',domain:'Math',skill:'Systems',d:2,q:'If y = 2x + 1 and y = x + 5, what is x?',o:['2','3','4','6'],a:2},
 {id:'m6',domain:'Math',skill:'Functions',d:2,q:'If f(x)=3x²−2, what is f(−2)?',o:['4','10','14','34'],a:1},
 {id:'m7',domain:'Math',skill:'Quadratics',d:3,q:'Which values solve x² − 7x + 12 = 0?',o:['−3 and −4','3 and 4','2 and 6','1 and 12'],a:1},
 {id:'m8',domain:'Math',skill:'Geometry',d:3,q:'A circle has area 49π. What is its circumference?',o:['7π','14π','49π','98π'],a:1},
 {id:'r1',domain:'Reading & Writing',skill:'Inference',d:1,p:'Lena arrived twenty minutes early, reviewed her notes twice, and chose a seat near the front. When the speaker entered, she immediately put her phone away.',q:'Which inference is best supported?',o:['Lena was uninterested in the event.','Lena was prepared and attentive.','Lena had forgotten why she came.','Lena planned to leave early.'],a:1},
 {id:'r2',domain:'Reading & Writing',skill:'Transitions',d:1,q:'The experiment produced an unexpected result. ___, the researchers repeated it with a larger sample.',o:['For example','Nevertheless','Therefore','Similarly'],a:2},
 {id:'r3',domain:'Reading & Writing',skill:'Grammar',d:1,q:'Which sentence is grammatically correct?',o:['The collection of maps are stored upstairs.','The collection of maps is stored upstairs.','The collection of maps were stored upstairs yesterday and is today.','The collection of maps have been stored upstairs.'],a:1},
 {id:'r4',domain:'Reading & Writing',skill:'Evidence',d:2,p:'A school moved its start time from 7:20 a.m. to 8:10 a.m. The following semester, average first-period attendance rose from 91% to 95%, while attendance in later periods changed little.',q:'Which claim is best supported?',o:['Later start times always improve grades.','The schedule change was associated with improved first-period attendance.','Students preferred every aspect of the new schedule.','Later periods became less important.'],a:1},
 {id:'r5',domain:'Reading & Writing',skill:'Words in Context',d:2,q:'In the sentence “The committee adopted a measured response rather than acting immediately,” measured most nearly means:',o:['calculated in units','careful and restrained','very lengthy','unpopular'],a:1},
 {id:'r6',domain:'Reading & Writing',skill:'Rhetorical Synthesis',d:2,q:'A student wants to emphasize a contrast between two studies. Which transition best serves that goal?',o:['Likewise,','For instance,','However,','Consequently,'],a:2},
 {id:'r7',domain:'Reading & Writing',skill:'Punctuation',d:3,q:'Choose the best punctuation: “The telescope revealed three objects ___ a comet, a distant galaxy, and a nebula.”',o:['objects, a comet','objects: a comet','objects; a comet','objects a comet'],a:1},
 {id:'r8',domain:'Reading & Writing',skill:'Analysis',d:3,p:'Researchers observed that urban gardens with a greater variety of flowering plants attracted more bee species. The study did not manipulate plant variety and did not measure bee populations before the gardens were created.',q:'Which statement most accurately evaluates the evidence?',o:['It proves plant variety causes bee diversity.','It supports an association but does not establish causation.','It proves bees cause gardens to contain more plants.','It provides no information about bees.'],a:1}
];
const TARGETED=[
 {id:'t-inf',domain:'Reading & Writing',skill:'Inference',aliases:['Inference','Reading Comprehension'],d:2,p:'After the principal announced a new phone policy, Maya reread the notice, placed her phone in her backpack, and reminded her friend to do the same before class.',q:'Which inference is best supported?',o:['Maya intends to ignore the policy.','Maya understands and plans to follow the policy.','Maya has lost her phone.','Maya wrote the policy.'],a:1},
 {id:'t-ana',domain:'Reading & Writing',skill:'Analysis',aliases:['Analysis'],d:2,p:'A survey found that students who used a planner more often also reported fewer missed assignments. The survey did not assign students to use planners.',q:'What does the evidence support?',o:['Planner use definitely causes fewer missed assignments.','There is an association, but causation is not established.','Missing assignments cause planner use in every case.','The survey contains no useful information.'],a:1},
 {id:'t-evi',domain:'Reading & Writing',skill:'Evidence',aliases:['Evidence','Supporting Details','Explicit Information'],d:2,p:'The library extended its hours by two hours each evening. During the next month, evening visits increased by 28%, while daytime visits were nearly unchanged.',q:'Which claim is best supported?',o:['Longer hours were associated with more evening library use.','Longer hours improved every student’s grades.','Daytime library use stopped.','Every visitor preferred the change.'],a:0},
 {id:'t-voc',domain:'Reading & Writing',skill:'Words in Context',aliases:['Precision','Vocabulary','Words in Context'],d:2,q:'In “The coach gave a concise explanation,” concise most nearly means:',o:['confusing','brief and clear','angry','highly technical'],a:1},
 {id:'t-use',domain:'Reading & Writing',skill:'Grammar',aliases:['Usage','Writing Mechanics','Grammar'],d:2,q:'Which sentence is correct?',o:['Neither of the answers are correct.','Neither of the answers is correct.','Neither of the answers were correct and is.','Neither of the answers have correct.'],a:1},
 {id:'t-org',domain:'Reading & Writing',skill:'Rhetorical Synthesis',aliases:['Organization','Purpose','Style','Writing Concepts','Rhetorical Synthesis'],d:2,q:'A writer wants to introduce a paragraph that explains why a proposed solution is preferable to two alternatives. Which opening best fits that purpose?',o:['Several alternatives exist.','However, the proposed approach offers two advantages the alternatives do not.','For example, the issue began last year.','Similarly, all three ideas have names.'],a:1},
 {id:'t-pun',domain:'Reading & Writing',skill:'Punctuation',aliases:['Punctuation','Writing Mechanics'],d:2,q:'Choose the best punctuation: “The project requires three materials ___ wood, glue, and paint.”',o:['materials, wood','materials: wood','materials; wood','materials wood'],a:1},
 {id:'t-num',domain:'Math',skill:'Number Sense',aliases:['Number Sense','Math Concepts'],d:2,q:'Which value is greatest?',o:['0.48','47%','1/2','0.49'],a:2},
 {id:'t-frac',domain:'Math',skill:'Fractions & Decimals',aliases:['Fractions & Decimals'],d:2,q:'What is 3/4 + 0.5?',o:['0.75','1.00','1.25','1.50'],a:2},
 {id:'t-data',domain:'Math',skill:'Data Analysis',aliases:['Data Analysis'],d:2,q:'The mean of 6, 8, 10, and x is 9. What is x?',o:['10','11','12','13'],a:2},
 {id:'t-pre',domain:'Math',skill:'Linear Equations',aliases:['Pre-Algebra','Linear Equations'],d:2,q:'Solve: 3(x + 2) = 21.',o:['5','7','9','15'],a:0},
 {id:'t-prob',domain:'Math',skill:'Problem Solving',aliases:['Problem Solving','Math Procedures'],d:2,q:'A car travels 180 miles in 3 hours at a constant rate. At that rate, how far will it travel in 4.5 hours?',o:['240','250','270','300'],a:2},
 {id:'t-geo',domain:'Math',skill:'Geometry',aliases:['Geometry','Measurement'],d:2,q:'A rectangle has length 12 and width 7. What is its area?',o:['19','38','84','168'],a:2}
];
const ALL=[...CORE,...TARGETED];
let running=false,answering=false,currentPlan=[];
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
async function context(){const{data:{session}}=await supabase.auth.getSession();if(!session)return{};const{data:p}=await supabase.from('profiles').select('id,role,first_name').eq('id',session.user.id).maybeSingle();if(p?.role!=='student')return{session,profile:p};const{data:s}=await supabase.from('students').select('*').eq('profile_id',p.id).maybeSingle();return{session,profile:p,student:s}}
function top(){return `<div class="top"><div class="logo">SAT<span>prep.io</span></div><div class="navlinks"><button class="linkbtn" id="diagExit">Dashboard</button></div></div>`}
function externalPriorities(student){const p=student?.recommended_path||{};const raw=p.external_priority_skills||p.priority_skills||[];return raw.map(x=>({skill:String(x.skill||x.source_skill||''),mastery:Number(x.mastery??1),source:x.source||'prior testing'})).filter(x=>x.skill).sort((a,b)=>a.mastery-b.mastery)}
function makePlan(student){const pri=externalPriorities(student);const targeted=[];for(const p of pri){const q=TARGETED.find(x=>!targeted.includes(x)&&x.aliases.some(a=>a.toLowerCase()===p.skill.toLowerCase()));if(q)targeted.push(q);if(targeted.length>=4)break}const core=[...CORE];if(!targeted.length)return core;const rw=targeted.filter(x=>x.domain!=='Math'),math=targeted.filter(x=>x.domain==='Math');const plan=[];core.forEach((q,i)=>{plan.push(q);if(i===3&&rw[0])plan.push(rw[0]);if(i===7&&math[0])plan.push(math[0]);if(i===11&&rw[1])plan.push(rw[1]);if(i===15&&(math[1]||rw[2]||targeted[3]))plan.push(math[1]||rw[2]||targeted[3])});for(const q of targeted)if(!plan.includes(q))plan.push(q);return plan}
function byIds(ids){return (ids||[]).map(id=>ALL.find(q=>q.id===id)).filter(Boolean)}
async function existingAttempt(student){const{data:attempts}=await supabase.from('diagnostic_attempts').select('id,created_at,summary').eq('student_id',student.id).neq('status','completed').order('created_at',{ascending:false}).limit(1);const attempt=attempts?.[0];if(!attempt)return null;const plan=byIds(attempt.summary?.question_plan);currentPlan=plan.length?plan:makePlan(student);const{data:responses,error}=await supabase.from('diagnostic_responses').select('question_key,is_correct').eq('attempt_id',attempt.id).order('created_at',{ascending:true});if(error)return null;const responseMap=new Map((responses||[]).map(r=>[r.question_key,r]));const results=currentPlan.filter(q=>responseMap.has(q.id)).map(q=>({...q,correct:!!responseMap.get(q.id).is_correct}));return{attemptId:attempt.id,index:Math.min(results.length,currentPlan.length),results}}
async function startDiagnostic(){const{student}=await context();if(!student||!student.onboarding_complete)return;let resume=await existingAttempt(student);if(!resume){currentPlan=makePlan(student);const external=externalPriorities(student).slice(0,8);const{data:attempt,error}=await supabase.from('diagnostic_attempts').insert({student_id:student.id,status:'in_progress',summary:{question_plan:currentPlan.map(q=>q.id),adaptive:true,external_priorities:external}}).select('id').single();if(error)return alert(error.message);resume={attemptId:attempt.id,index:0,results:[]}}running=true;if(resume.index>=currentPlan.length)return finish(student,resume.attemptId,resume.results);runQuestion(student,resume.attemptId,resume.index,resume.results,Date.now())}
function runQuestion(student,attemptId,index,results,started){const q=currentPlan[index],app=document.querySelector('#app');answering=false;app.innerHTML=top()+`<main class="wrap"><div class="card" style="max-width:820px;margin:auto"><div class="row"><div><div class="eyebrow">ADAPTIVE INITIAL DIAGNOSTIC</div><h2 style="margin:0">${esc(q.domain)}</h2></div><span class="badge">${index+1} of ${currentPlan.length}</span></div><div class="progress" style="margin:16px 0 24px"><div style="width:${Math.round(index/currentPlan.length*100)}%"></div></div>${q.p?`<div class="passage">${esc(q.p)}</div>`:''}<div class="question">${esc(q.q)}</div>${q.o.map((x,i)=>`<button class="option" data-a="${i}"><strong>${String.fromCharCode(65+i)}.</strong> ${esc(x)}</button>`).join('')}<p class="small">Choose the best answer. Your progress is saved after every question.</p></div></main>`;document.querySelector('#diagExit').onclick=()=>{running=false;location.assign('/?app=1')};document.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{if(answering)return;answering=true;document.querySelectorAll('[data-a]').forEach(x=>x.disabled=true);const selected=Number(b.dataset.a),correct=selected===q.a,response_ms=Date.now()-started;const{error}=await supabase.from('diagnostic_responses').insert({attempt_id:attemptId,student_id:student.id,question_key:q.id,domain:q.domain,skill_key:q.skill,difficulty:q.d,selected_answer:selected,correct_answer:q.a,is_correct:correct,response_ms});if(error){answering=false;document.querySelectorAll('[data-a]').forEach(x=>x.disabled=false);return alert(`Your answer could not be saved: ${error.message}`)}const next=[...results,{...q,correct}];if(index<currentPlan.length-1)runQuestion(student,attemptId,index+1,next,Date.now());else finish(student,attemptId,next)})}
async function finish(student,attemptId,results){const math=results.filter(x=>x.domain==='Math'),rw=results.filter(x=>x.domain!=='Math'),score=a=>a.length?a.filter(x=>x.correct).length/a.length:0,mathScore=score(math),rwScore=score(rw),overall=(mathScore+rwScore)/2,bySkill={};results.forEach(x=>{bySkill[x.skill]??={right:0,total:0,domain:x.domain};bySkill[x.skill].total++;if(x.correct)bySkill[x.skill].right++});const ranked=Object.entries(bySkill).map(([skill,v])=>({skill,domain:v.domain,mastery:v.right/v.total,items:v.total})).sort((a,b)=>a.mastery-b.mastery),diag={priority_skills:ranked.slice(0,6),strengths:[...ranked].sort((a,b)=>b.mastery-a.mastery).slice(0,4),diagnostic_version:'adaptive-v2',question_plan:currentPlan.map(q=>q.id),adaptive:true},recommended=overall>=.8?'Accelerated SAT/PSAT Path':overall>=.55?'Core SAT/PSAT Path':'Foundation-Building Path',now=new Date().toISOString();const{error:aErr}=await supabase.from('diagnostic_attempts').update({status:'completed',completed_at:now,math_score:mathScore,rw_score:rwScore,overall_score:overall,recommended_start:recommended,summary:diag}).eq('id',attemptId);if(aErr)return alert(`Diagnostic result could not be saved: ${aErr.message}`);const current=student.recommended_path&&typeof student.recommended_path==='object'?student.recommended_path:{};const merged={...current,diagnostic:diag,diagnostic_priority_skills:diag.priority_skills,diagnostic_strengths:diag.strengths,diagnostic_completed_at:now};const{error:sErr}=await supabase.from('students').update({diagnostic_completed_at:now,diagnostic_math_mastery:mathScore,diagnostic_rw_mastery:rwScore,recommended_path:merged,onboarding_complete:true}).eq('id',student.id);if(sErr)return alert(`Learning path could not be saved: ${sErr.message}`);for(const x of ranked)await supabase.from('skill_mastery').upsert({student_id:student.id,skill_key:x.skill,mastery:x.mastery,items_attempted:x.items,updated_at:now},{onConflict:'student_id,skill_key'});running=false;renderResults(mathScore,rwScore,recommended,diag,externalPriorities(student))}
function renderResults(math,rw,recommended,diag,external){const app=document.querySelector('#app');app.innerHTML=top()+`<main class="wrap"><section class="hero"><div class="eyebrow">DIAGNOSTIC COMPLETE</div><h1>Your starting path is ready.</h1><p>Your prior testing and this diagnostic now work together. SATprep.io will continue updating the model as you complete lessons.</p></section><section class="grid"><div class="card c4"><div class="label">Math readiness</div><div class="metric">${Math.round(math*100)}%</div></div><div class="card c4"><div class="label">Reading & Writing readiness</div><div class="metric">${Math.round(rw*100)}%</div></div><div class="card c4"><div class="label">Recommended start</div><div style="font-size:21px;font-weight:850;color:var(--navy);margin-top:8px">${esc(recommended)}</div></div>${external.length?`<div class="card c12"><h2>Prior-testing areas we deliberately checked</h2><p class="muted">These came from previously uploaded assessment evidence and influenced this diagnostic.</p>${external.slice(0,6).map(x=>`<span class="badge warn" style="margin:4px">${esc(x.skill)}</span>`).join('')}</div>`:''}<div class="card c6"><h2>Diagnostic priorities</h2>${diag.priority_skills.map(x=>`<div class="lesson"><div><strong>${esc(x.skill)}</strong><div class="small">${esc(x.domain)}</div></div><span class="badge ${x.mastery>=.8?'good':'warn'}">${Math.round(x.mastery*100)}%</span></div>`).join('')}</div><div class="card c6"><h2>Diagnostic strengths</h2>${diag.strengths.map(x=>`<div class="lesson"><div><strong>${esc(x.skill)}</strong><div class="small">${esc(x.domain)}</div></div><span class="badge good">${Math.round(x.mastery*100)}%</span></div>`).join('')}</div><div class="card c12"><button class="btn" id="diagContinue">Go to my learning path</button></div></section></main>`;document.querySelector('#diagExit').onclick=document.querySelector('#diagContinue').onclick=()=>location.assign('/?app=1')}
async function enhance(){if(running)return;const params=new URLSearchParams(location.search);if(params.get('app')!=='1'||params.get('openBilling')==='1')return;const{profile,student}=await context();if(profile?.role!=='student'||!student||student.diagnostic_completed_at||!student.onboarding_complete)return;if(document.querySelector('#startDiagnosticCard'))return;const main=document.querySelector('main');if(!main)return;const resume=await existingAttempt(student),completed=resume?.index||0,pri=externalPriorities(student),estimated=(resume?currentPlan:makePlan(student)).length;main.innerHTML=`<section class="hero" id="startDiagnosticCard"><div class="eyebrow">YOUR FIRST MISSION</div><h1>${completed?'Continue your diagnostic':'Confirm your personalized starting point'}</h1><p>${completed?`You completed ${completed} of ${estimated} questions. Pick up exactly where you left off.`:pri.length?'SATprep.io already has prior testing evidence. This diagnostic will sample the full SAT/PSAT skill set and add extra confirmation questions in the areas your earlier testing flagged.':'Before lessons begin, SATprep.io needs a quick picture of what you already know.'}</p></section><section class="card" style="max-width:760px;margin:18px auto"><h2>${completed?'Your progress is saved':pri.length?'Prior testing is shaping this diagnostic':'A personalized path starts here'}</h2>${pri.length?`<p class="muted">Current evidence suggests we should pay extra attention to:</p><div>${pri.slice(0,6).map(x=>`<span class="badge warn" style="margin:4px">${esc(x.skill)}</span>`).join('')}</div>`:'<p class="muted">This diagnostic samples Math and Reading & Writing skills and establishes an initial baseline.</p>'}<div class="notice" style="margin-top:14px"><strong>${completed?`${estimated-completed} questions remaining`:`${estimated} questions`}</strong> · Core coverage plus evidence-driven confirmation · Results immediately shape your learning path.</div><button class="btn" id="startDiagnostic" style="margin-top:14px">${completed?'Resume diagnostic':'Start my diagnostic'}</button></section>`;document.querySelector('#startDiagnostic').onclick=startDiagnostic}
const obs=new MutationObserver(()=>setTimeout(enhance,0));obs.observe(document.documentElement,{subtree:true,childList:true});setTimeout(enhance,200);
