import {supabase} from './supabase.js';

const STORAGE='satprep_live_pilot_token',RELOAD='satprep_live_pilot_path_reloaded';
const TOKEN=/^[A-Za-z0-9_-]{32,128}$/;
let parentPilot=false,busy=false;
const params=()=>new URLSearchParams(location.search);
const incoming=params().get('pilot');
if(TOKEN.test(String(incoming||'')))localStorage.setItem(STORAGE,incoming);
const storedToken=()=>{const v=localStorage.getItem(STORAGE)||'';return TOKEN.test(v)?v:null};

async function authedPost(url,body={}){const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Please sign in again.');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed.');return data}
function autoOpenParentSignup(){if(!TOKEN.test(String(incoming||''))||sessionStorage.getItem('satprep_pilot_signup_opened'))return;sessionStorage.setItem('satprep_pilot_signup_opened','1');setTimeout(()=>{document.querySelector('[data-auth="signup"]')?.click();setTimeout(()=>document.querySelector('#parentStart')?.click(),30)},180)}
function pilotNotice(){if(document.querySelector('#livePilotNotice'))return;const main=document.querySelector('main');if(!main)return;const n=document.createElement('div');n.id='livePilotNotice';n.className='notice';n.style.margin='14px auto';n.style.maxWidth='1040px';n.innerHTML='<strong>LIVE FAMILY PILOT</strong> · This household is using test-only access. Billing is bypassed and pilot activity is excluded from commercial content activation.';main.prepend(n)}
function tuneParentUi(){if(!parentPilot)return;pilotNotice();const billing=document.querySelector('#manageBilling');if(billing)billing.style.display='none';const save=document.querySelector('#saveAndBilling');if(save)save.textContent='Save child & continue';const intro=document.querySelector('#parentFamilySetup .notice');if(intro&&/Family plan/i.test(intro.textContent||''))intro.textContent='This live pilot does not require billing.'}
async function interceptPilotChildSave(event){const button=event.target?.closest?.('#saveAndBilling');if(!button||!parentPilot)return;event.preventDefault();event.stopImmediatePropagation();const container=button.closest('#parentFamilySetup')||document;const first_name=container.querySelector('#childFirst')?.value.trim(),last_name=container.querySelector('#childLast')?.value.trim(),date_of_birth=container.querySelector('#childDob')?.value||'',grade_level=Number(container.querySelector('#childGrade')?.value||0)||null,target_exam=container.querySelector('#childExam')?.value||'PSAT',msg=container.querySelector('#childSaveMessage');if(!first_name||!last_name||!date_of_birth){if(msg)msg.innerHTML='<div class="error">Enter the student name and date of birth.</div>';return}button.disabled=true;try{await authedPost('/api/parent-student',{first_name,last_name,date_of_birth,grade_level,target_exam});location.assign('/?app=1&pilot=1')}catch(error){button.disabled=false;if(msg)msg.innerHTML=`<div class="error">${String(error.message||'Unable to save the student.')}</div>`}}
document.addEventListener('click',interceptPilotChildSave,true);

async function syncStudentPath(profile){if(profile?.role!=='student'||!profile.is_test_account)return;try{const result=await authedPost('/api/live-pilot-sync-path',{});if(result.changed&&!sessionStorage.getItem(RELOAD)){sessionStorage.setItem(RELOAD,'1');location.reload()}}catch(error){console.warn('live pilot path sync',error?.message||error)}}
async function refreshPilotState(){if(busy)return;busy=true;try{const{data:{session}}=await supabase.auth.getSession();if(!session){autoOpenParentSignup();return}const{data:profile}=await supabase.from('profiles').select('id,role,household_id,is_test_account').eq('id',session.user.id).maybeSingle();if(!profile)return;if(profile.role==='parent'){const token=storedToken();let claimed=null;if(token&&!profile.is_test_account){claimed=await authedPost('/api/live-pilot-claim',{token});parentPilot=!!claimed.pilot}else parentPilot=!!profile.is_test_account;if(parentPilot){tuneParentUi();if(claimed?.student_count===0&&!params().get('onboarding')&&params().get('app')!=='1')location.assign('/?app=1&onboarding=child&pilot=1');else if(claimed?.student_count===0&&params().get('app')==='1'&&!params().get('onboarding'))location.assign('/?app=1&onboarding=child&pilot=1')}}else if(profile.role==='student'){await syncStudentPath(profile)}}catch(error){console.warn('live pilot bridge',error?.message||error)}finally{busy=false}}
const observer=new MutationObserver(()=>{tuneParentUi();setTimeout(refreshPilotState,50)});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(refreshPilotState,250);supabase.auth.onAuthStateChange(()=>setTimeout(refreshPilotState,150));
