import "./style.css";
import { supabase, configured } from "./supabase.js";
import { CURRICULUM } from "./curriculum.js";

const app = document.querySelector("#app");
let session = null;
let profile = null;
let student = null;
let progress = {};
let skills = {};
let lessonState = null;
let authMode = "login";

const esc = s => String(s ?? "").replace(/[&<>"]/g, m => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const pct = x => Math.round((x || 0) * 100);
const fullName = p => [p?.first_name, p?.last_name].filter(Boolean).join(" ") || p?.email || "User";
function top(){return `<div class="top"><div class="logo">SAT<span>prep.io</span></div><div class="navlinks">${session ? `<button class="linkbtn" id="dashBtn">Dashboard</button><button class="linkbtn" id="signoutBtn">Sign out</button>` : ""}</div></div>`}
function bindTop(){document.querySelector("#dashBtn")?.addEventListener("click",()=>{lessonState=null;renderDashboard()});document.querySelector("#signoutBtn")?.addEventListener("click",async()=>{await supabase.auth.signOut();location.assign("/")})}
function renderConfig(){app.innerHTML=top()+`<main class="wrap"><div class="auth"><div class="card"><h1>SATprep.io</h1><div class="notice"><strong>Application is ready for its cloud connection.</strong><br><br>Add <code>VITE_SUPABASE_URL</code> and <code>VITE_SUPABASE_ANON_KEY</code> as environment variables in Vercel.</div></div></div></main>`}
function renderAuth(message=""){app.innerHTML=top()+`<main class="wrap"><div class="auth"><div class="card"><h1 style="margin-bottom:4px">Welcome to SATprep.io</h1><p class="muted">Adaptive SAT and PSAT preparation that learns the student.</p><div class="tabs"><button class="tab ${authMode==="login"?"active":""}" id="loginTab">Sign in</button><button class="tab ${authMode==="signup"?"active":""}" id="signupTab">Create account</button></div>${message?`<div class="${message.startsWith("Check")?"success":"error"}">${esc(message)}</div>`:""}<form id="authForm">${authMode==="signup"?`<div class="field"><label>Account type</label><select id="role"><option value="student">Student</option><option value="parent">Parent</option></select></div><div class="field"><label>First name</label><input id="firstName" required /></div><div class="field"><label>Last name</label><input id="lastName" required /></div>`:""}<div class="field"><label>Email</label><input id="email" type="email" required /></div><div class="field"><label>Password</label><input id="password" type="password" minlength="8" required /></div><button class="btn" type="submit">${authMode==="login"?"Sign in":"Create account"}</button></form></div></div></main>`;document.querySelector("#loginTab").onclick=()=>{authMode="login";renderAuth()};document.querySelector("#signupTab").onclick=()=>{authMode="signup";renderAuth()};document.querySelector("#authForm").onsubmit=handleAuth}
async function handleAuth(e){e.preventDefault();const email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value;if(authMode==="login"){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)renderAuth(error.message)}else{const role=document.querySelector("#role").value,first_name=document.querySelector("#firstName").value.trim(),last_name=document.querySelector("#lastName").value.trim();const{data,error}=await supabase.auth.signUp({email,password,options:{data:{role,first_name,last_name}}});if(error)return renderAuth(error.message);if(!data.session)renderAuth("Check your email to confirm your account, then sign in.")}}
async function loadData(){const uid=session.user.id;const{data:p}=await supabase.from("profiles").select("*").eq("id",uid).maybeSingle();profile=p;if(!profile)return;if(profile.role==="student"){const{data:s}=await supabase.from("students").select("*").eq("profile_id",uid).maybeSingle();student=s}else if(profile.role==="parent"){const{data:links}=await supabase.from("parent_students").select("student_id").eq("parent_profile_id",uid).limit(1);if(links?.length){const{data:s}=await supabase.from("students").select("*").eq("id",links[0].student_id).maybeSingle();student=s}}if(student){const{data:pr}=await supabase.from("lesson_progress").select("*").eq("student_id",student.id);progress=Object.fromEntries((pr||[]).map(x=>[x.lesson_key,x]));const{data:sk}=await supabase.from("skill_mastery").select("*").eq("student_id",student.id);skills=Object.fromEntries((sk||[]).map(x=>[x.skill_key,x]))}}
function roleDashboard(){if(profile?.role==="admin")return renderAdmin();if(profile?.role==="parent")return renderParent();return renderStudent()}function renderDashboard(){roleDashboard()}
function renderStudent(){if(!student?.onboarding_complete)return renderOnboarding();const done=Object.keys(progress).filter(k=>progress[k].completed_at).length,scored=Object.values(progress).filter(x=>x.best_score!=null),avg=scored.length?scored.reduce((a,b)=>a+Number(b.best_score),0)/scored.length:0,next=CURRICULUM.find(l=>unlocked(l)&&!progress[l.id]?.completed_at);app.innerHTML=top()+`<main class="wrap"><section class="hero"><h1>Welcome back, ${esc(profile.first_name)}.</h1><p>Learn the skill. Prove mastery. Keep moving toward ${student.target_score||"your target"}.</p></section><section class="grid"><div class="card c3"><div class="label">Lessons Complete</div><div class="metric">${done}</div></div><div class="card c3"><div class="label">Average Mastery</div><div class="metric">${pct(avg)}%</div></div><div class="card c3"><div class="label">Target Score</div><div class="metric">${student.target_score||"—"}</div></div><div class="card c3"><div class="label">Exam</div><div class="metric" style="font-size:23px">${esc(student.target_exam||"PSAT")}</div></div><div class="card c8"><h2>Learning Path</h2>${CURRICULUM.map(l=>{const u=unlocked(l),p=progress[l.id];return `<div class="lesson ${u?"":"locked"}"><div><strong>Week ${l.week} — ${esc(l.title)}</strong><div class="small">${esc(l.domain)}</div></div><div class="right"><span class="badge">${p?.best_score!=null?pct(Number(p.best_score))+"%":u?"Ready":"Locked"}</span><button class="btn" data-lesson="${l.id}" ${u?"":"disabled"}>${p?.completed_at?"Review":"Start"}</button></div></div>`}).join("")}</div><div class="card c4"><h2>Next Mission</h2>${next?`<p><strong>${esc(next.title)}</strong></p><button class="btn" data-lesson="${next.id}">Begin</button>`:`<p>Current assigned lessons are complete.</p>`}</div></section></main>`;bindTop();document.querySelectorAll("[data-lesson]").forEach(b=>b.onclick=()=>startLesson(b.dataset.lesson))}
function unlocked(l){if(!l.prerequisite)return true;const p=progress[l.prerequisite];return p&&Number(p.best_score)>=l.required}
function renderOnboarding(){app.innerHTML=top()+`<main class="wrap"><div class="auth"><div class="card"><h1>Build your learner profile</h1><form id="onboard"><div class="field"><label>Current grade</label><select id="grade">${Array.from({length:9},(_,i)=>`<option value="${i+4}" ${Number(student?.grade_level)===i+4?"selected":""}>${i+4}</option>`).join("")}</select></div><div class="field"><label>Current math course</label><input id="mathCourse" value="${esc(student?.math_course||"")}" /></div><div class="field"><label>Target exam</label><select id="targetExam"><option ${student?.target_exam==="PSAT"?"selected":""}>PSAT</option><option ${student?.target_exam==="PSAT/NMSQT"?"selected":""}>PSAT/NMSQT</option><option ${student?.target_exam==="SAT"?"selected":""}>SAT</option></select></div><div class="field"><label>Target score</label><input id="targetScore" type="number" value="${Number(student?.target_score)||1300}" /></div><button class="btn">Save & begin</button></form></div></div></main>`;bindTop();document.querySelector("#onboard").onsubmit=async e=>{e.preventDefault();const updates={grade_level:Number(document.querySelector("#grade").value),math_course:document.querySelector("#mathCourse").value,target_exam:document.querySelector("#targetExam").value,target_score:Number(document.querySelector("#targetScore").value),onboarding_complete:true};const{error}=await supabase.from("students").update(updates).eq("id",student.id);if(error)return alert(error.message);Object.assign(student,updates);renderStudent()}}
function startLesson(id){const lesson=CURRICULUM.find(x=>x.id===id);if(!lesson)return;lessonState={lesson,index:0,selected:null,checked:false,started:Date.now(),correct:0,answered:0,results:[]};renderLesson()}
function renderLesson(){const{lesson,index}=lessonState,q=lesson.qs[index],lastResult=lessonState.results[index];app.innerHTML=top()+`<main class="wrap"><div class="card"><div class="row"><div><div class="eyebrow">LEARNING SESSION</div><h2>${esc(lesson.title)}</h2></div><span class="badge">${index+1} of ${lesson.qs.length}</span></div><div class="progress" style="margin:12px 0 22px"><div style="width:${Math.round((index+1)/lesson.qs.length*100)}%"></div></div><div class="question">${esc(q.q)}</div>${q.o.map((o,i)=>`<button class="option ${lessonState.selected===i?"sel":""}" data-choice="${i}" ${lessonState.checked?"disabled":""}>${esc(o)}</button>`).join("")}${lessonState.checked?`<div class="${lastResult?.correct?"success":"notice"}" style="margin-top:14px"><strong>${lastResult?.correct?"Correct.":"Not quite."}</strong> ${lastResult?.correct?"Nice work—keep going.":`The correct answer is ${esc(q.o[q.a])}.`}</div>`:""}<div class="row" style="margin-top:18px"><button class="btn secondary" id="pauseBtn">Pause</button>${lessonState.checked?`<button class="btn" id="nextBtn">${index===lesson.qs.length-1?"Finish session":"Next"}</button>`:`<button class="btn" id="checkBtn" ${lessonState.selected===null?"disabled":""}>Check answer</button>`}</div></div></main>`;bindTop();document.querySelector("#pauseBtn").onclick=pauseLesson;document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{if(lessonState.checked)return;lessonState.selected=Number(b.dataset.choice);renderLesson()});document.querySelector("#checkBtn")?.addEventListener("click",checkAnswer);document.querySelector("#nextBtn")?.addEventListener("click",nextQuestion)}
async function checkAnswer(){const{lesson,index}=lessonState,q=lesson.qs[index];if(lessonState.checked||lessonState.selected===null)return;lessonState.checked=true;lessonState.answered++;const ok=lessonState.selected===q.a;if(ok)lessonState.correct++;const response_ms=Math.max(0,Date.now()-lessonState.started);lessonState.results[index]={skill:q.skill,correct:ok,response_ms};const{error}=await supabase.from("question_attempts").insert({student_id:student.id,lesson_key:lesson.id,question_index:index,skill_key:q.skill,selected_answer:lessonState.selected,correct_answer:q.a,is_correct:ok,response_ms});if(error){lessonState.checked=false;lessonState.answered--;if(ok)lessonState.correct--;lessonState.results[index]=null;return alert(`Your answer could not be saved: ${error.message}`)}renderLesson()}
async function pauseLesson(){if(lessonState?.answered){const score=lessonState.correct/lessonState.answered;await supabase.from("lesson_progress").upsert({student_id:student.id,lesson_key:lessonState.lesson.id,current_question:lessonState.index,best_score:Math.max(Number(progress[lessonState.lesson.id]?.best_score||0),score),last_score:score,updated_at:new Date().toISOString()},{onConflict:"student_id,lesson_key"})}lessonState=null;await loadData();renderStudent()}
async function finalizeLesson(){const s=lessonState,score=s.answered?s.correct/s.answered:0,now=new Date().toISOString(),prior=Number(progress[s.lesson.id]?.best_score||0),best=Math.max(prior,score);const{error}=await supabase.from("lesson_progress").upsert({student_id:student.id,lesson_key:s.lesson.id,current_question:0,best_score:best,last_score:score,completed_at:now,updated_at:now},{onConflict:"student_id,lesson_key"});if(error)return alert(`Your lesson result could not be saved: ${error.message}`);const bySkill={};for(const r of s.results.filter(Boolean)){bySkill[r.skill]??={right:0,total:0};bySkill[r.skill].total++;if(r.correct)bySkill[r.skill].right++}for(const[skill,v]of Object.entries(bySkill)){const existing=skills[skill],oldItems=Number(existing?.items_attempted||0),oldMastery=Number(existing?.mastery||0),newItems=oldItems+v.total,newMastery=newItems?((oldMastery*oldItems)+v.right)/newItems:v.right/v.total;await supabase.from("skill_mastery").upsert({student_id:student.id,skill_key:skill,mastery:newMastery,items_attempted:newItems,updated_at:now},{onConflict:"student_id,skill_key"})}lessonState=null;await loadData();app.innerHTML=top()+`<main class="wrap"><section class="hero"><div class="eyebrow">SESSION COMPLETE</div><h1>${pct(score)}% on ${esc(s.lesson.title)}</h1><p>Your result was saved. Your mastery, learning path and Road to Test Day have been updated.</p><button class="btn" id="lessonDone">Continue</button></section></main>`;bindTop();document.querySelector("#lessonDone").onclick=renderStudent}
async function nextQuestion(){if(lessonState.index<lessonState.lesson.qs.length-1){lessonState.index++;lessonState.selected=null;lessonState.checked=false;lessonState.started=Date.now();renderLesson()}else await finalizeLesson()}
function renderParent(){app.innerHTML=top()+`<main class="wrap"><section class="hero"><h1>Parent Dashboard</h1><p>${student?esc(student.display_name||"Student"):"No student linked yet"}</p></section></main>`;bindTop()}
async function renderAdmin(){app.innerHTML=top()+`<main class="wrap"><section class="hero"><h1>Administrator Dashboard</h1><p>${esc(fullName(profile))}</p></section></main>`;bindTop()}
async function boot(){
  const params=new URLSearchParams(location.search);
  const appRequested=params.get("app")==="1" || params.get("billing")==="success";
  if(!appRequested) return;
  if(!configured) return renderConfig();
  const {data:{session:s}}=await supabase.auth.getSession();session=s;
  supabase.auth.onAuthStateChange(async(_event,s2)=>{session=s2;if(!session){profile=null;student=null;progress={};skills={};location.assign("/")}else{await loadData();roleDashboard()}});
  if(!session){location.assign("/");return}
  await loadData();roleDashboard();
}
boot();