import { supabase } from "./supabase.js";

const esc=s=>String(s??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[m]));
let activeSession=null;

function renderHome(){
 const app=document.querySelector("#app"),signedIn=!!activeSession;
 app.innerHTML=`<header class="marketing-nav"><div class="logo">SAT<span>prep.io</span></div><nav class="marketing-links"><a href="#how">How it works</a><a href="#parents">For parents</a><a href="#pricing">Pricing</a></nav><div class="marketing-actions">${signedIn?`<button class="btn" id="goDashboard">Dashboard</button>`:`<button class="btn ghost" data-auth="login">Log in</button><button class="btn" data-auth="signup">Get started free</button>`}</div></header>
 <main class="marketing-page"><section class="marketing-hero"><div class="hero-copy"><div class="eyebrow">Adaptive SAT & PSAT preparation</div><h1>Stop guessing what to study next.</h1><p class="lead">SATprep.io learns what a student knows, finds the skills holding them back, and builds a personalized path toward their target score.</p><div class="hero-actions">${signedIn?`<button class="btn btn-large" id="heroDashboard">Go to my dashboard</button>`:`<button class="btn btn-large" data-auth="signup">Get started for free</button><button class="btn ghost btn-large" data-auth="login">Already have an account? Log in</button>`}</div><div class="trust-row"><span>✓ 14-day free trial</span><span>✓ Personalized learning path</span><span>✓ Parent progress dashboard</span><span>✓ Cancel anytime</span></div></div><div class="score-card"><div class="score-top"><span>Personalized Readiness</span><span class="badge good">On track</span></div><div class="score-target">Target Score <strong>1300</strong></div><div class="mini-skill"><span>Reading & Writing</span><strong>81%</strong></div><div class="progress"><div style="width:81%"></div></div><div class="mini-skill"><span>Math</span><strong>72%</strong></div><div class="progress"><div style="width:72%"></div></div><div class="next-box"><small>NEXT RECOMMENDED SKILL</small><strong>Linear equations</strong><span>Chosen from performance, not a generic calendar.</span></div></div></section>
 <section class="proof-strip"><div><strong>Adaptive</strong><span>Lessons change as performance changes.</span></div><div><strong>Measurable</strong><span>Mastery, attempts and progress are tracked.</span></div><div><strong>Connected</strong><span>Students learn. Parents see the big picture.</span></div><div><strong>Flexible</strong><span>Continue on a computer, tablet or iPad.</span></div></section>
 <section class="marketing-section" id="how"><div class="section-heading"><span>HOW IT WORKS</span><h2>A smarter path from today's skills to test-day confidence.</h2></div><div class="feature-grid"><article><b>01</b><h3>Find the starting point</h3><p>Goals, prior testing and diagnostic performance establish what the student already knows and where instruction should begin.</p></article><article><b>02</b><h3>Teach before testing</h3><p>Students learn the underlying math, reading and writing skills—not just test tricks or endless question drilling.</p></article><article><b>03</b><h3>Prove mastery</h3><p>Performance is measured by skill. Weak areas trigger reinforcement while mastered material unlocks more advanced work.</p></article><article><b>04</b><h3>Keep adapting</h3><p>The learning path evolves with every session so limited study time is spent where it can make the greatest difference.</p></article></div></section>
 <section class="marketing-section parent-section" id="parents"><div><span class="eyebrow">Built for students. Visible to parents.</span><h2>Know whether the preparation is actually working.</h2><p>Parents can follow completed sessions, skill mastery, strengths, weaknesses, target-score progress and what SATprep.io recommends next—without hovering over every practice problem.</p>${signedIn?`<button class="btn" id="parentDashboard">Open dashboard</button>`:`<button class="btn" data-auth="signup">Create your family account</button>`}</div><div class="parent-panel"><div><span>This week</span><strong>2 / 2 sessions</strong></div><div><span>Current strength</span><strong>Reading comprehension</strong></div><div><span>Needs attention</span><strong>Linear equations</strong></div><div><span>Learning path</span><strong>On track</strong></div></div></section>
 <section class="marketing-section pricing-section" id="pricing"><div class="section-heading"><span>SIMPLE PRICING</span><h2>Start free. Choose the plan that fits your family.</h2><p>Every paid plan begins with a 14-day free trial.</p></div><div class="price-grid"><article><h3>Individual</h3><div class="price">$19.95<small>/month</small></div><p>One student plus parent/guardian access.</p><strong>Or $199/year</strong>${signedIn?``:`<button class="btn" data-auth="signup">Start free</button>`}</article><article class="featured-price"><div class="popular">FAMILY VALUE</div><h3>Family</h3><div class="price">$29.95<small>/month</small></div><p>Up to three students plus parent/guardian access.</p><strong>Or $299/year</strong>${signedIn?``:`<button class="btn" data-auth="signup">Start free</button>`}</article></div></section>
 <section class="final-cta"><h2>Give every study session a purpose.</h2><p>Build a personalized SAT or PSAT learning path and see exactly what should come next.</p>${signedIn?`<button class="btn btn-large" id="finalDashboard">Go to my dashboard</button>`:`<button class="btn btn-large" data-auth="signup">Get started for free</button><div class="small">14-day free trial · Cancel anytime</div>`}</section></main><footer>SATprep.io · Adaptive SAT & PSAT preparation</footer>`;
 document.querySelectorAll("[data-auth]").forEach(b=>b.onclick=()=>openAuth(b.dataset.auth));
 document.querySelectorAll("#goDashboard,#heroDashboard,#parentDashboard,#finalDashboard").forEach(b=>b.onclick=()=>location.assign("/?app=1"));
}

function shell(inner){document.querySelector("#app").innerHTML=`<div class="top"><div class="logo">SAT<span>prep.io</span></div><div class="navlinks"><button class="linkbtn" id="marketingHome">Home</button></div></div><main class="wrap"><div class="auth"><div class="card">${inner}</div></div></main>`;document.querySelector("#marketingHome").onclick=renderHome}
function openAuth(mode){if(mode==="signup")return signupStart();shell(`<h1 style="margin-bottom:4px">Welcome back</h1><p class="muted">Sign in to continue your SAT or PSAT preparation.</p><div id="authMessage"></div><form id="loginForm"><div class="field"><label>Email</label><input id="email" type="email" autocomplete="email" required /></div><div class="field"><label>Password</label><input id="password" type="password" minlength="8" required /></div><button class="btn">Sign in</button></form><p class="small">New to SATprep.io? <button class="linkbtn" id="switchSignup">Create an account</button></p>`);document.querySelector("#switchSignup").onclick=signupStart;document.querySelector("#loginForm").onsubmit=async e=>{e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:document.querySelector("#email").value.trim(),password:document.querySelector("#password").value});if(error)return document.querySelector("#authMessage").innerHTML=`<div class="error">${esc(error.message)}</div>`;location.assign("/?app=1")}}
function signupStart(){shell(`<div class="eyebrow">CREATE YOUR ACCOUNT</div><h1>Who is setting up SATprep.io?</h1><p class="muted">We'll use the right setup for your family and age.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:22px"><button class="btn secondary" id="parentStart">Parent or Guardian</button><button class="btn secondary" id="studentStart">Student</button></div><p class="small" style="margin-top:20px">Already have an account? <button class="linkbtn" id="switchLogin">Log in</button></p>`);document.querySelector("#parentStart").onclick=parentSignup;document.querySelector("#studentStart").onclick=studentAge;document.querySelector("#switchLogin").onclick=()=>openAuth("login")}
function parentSignup(){shell(`<div class="eyebrow">PARENT / GUARDIAN</div><h1>Create your family account</h1><p class="muted">You'll manage student access, progress and billing.</p><div id="msg"></div><form id="parentForm"><div class="field"><label>First name</label><input id="pFirst" autocomplete="given-name" required></div><div class="field"><label>Last name</label><input id="pLast" autocomplete="family-name" required></div><div class="field"><label>Email</label><input id="pEmail" type="email" required></div><div class="field"><label>Password</label><input id="pPass" type="password" minlength="8" required></div><button class="btn">Create parent account</button></form><button class="linkbtn" id="backSignup">← Back</button>`);document.querySelector("#backSignup").onclick=signupStart;document.querySelector("#parentForm").onsubmit=async e=>{e.preventDefault();const{data,error}=await supabase.auth.signUp({email:document.querySelector("#pEmail").value.trim(),password:document.querySelector("#pPass").value,options:{data:{role:"parent",first_name:document.querySelector("#pFirst").value.trim(),last_name:document.querySelector("#pLast").value.trim()}}});if(error)return document.querySelector("#msg").innerHTML=`<div class="error">${esc(error.message)}</div>`;if(data.session)location.assign("/?app=1");else document.querySelector("#msg").innerHTML=`<div class="success">Check your email to confirm your account, then log in.</div>`}}
function studentAge(){shell(`<div class="eyebrow">STUDENT</div><h1>First, how old are you?</h1><p class="muted">We ask age first so we can use the right account setup.</p><div class="field"><label>Age</label><select id="age"><option value="">Choose age</option>${Array.from({length:14},(_,i)=>`<option value="${i+7}">${i+7}${i===13?"+":""}</option>`).join("")}</select></div><button class="btn" id="ageNext">Continue</button><button class="linkbtn" id="backSignup">← Back</button>`);document.querySelector("#backSignup").onclick=signupStart;document.querySelector("#ageNext").onclick=()=>{const age=Number(document.querySelector("#age").value);if(!age)return alert("Please choose your age.");age<13?under13():teenSignup(age)}}
function under13(){shell(`<div class="eyebrow">PARENT APPROVAL</div><h1>Let's get a parent or guardian.</h1><div class="notice">Because you're under 13, a parent or guardian needs to finish setting up SATprep.io before we create your student account.</div><p class="small">Enter only your parent or guardian's email. We won't ask for your name yet.</p><div id="msg"></div><form id="guardianForm"><div class="field"><label>Parent or guardian email</label><input id="guardianEmail" type="email" autocomplete="email" required></div><button class="btn">Send setup request</button></form><button class="linkbtn" id="backAge">← Back</button>`);document.querySelector("#backAge").onclick=studentAge;document.querySelector("#guardianForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,msg=document.querySelector("#msg"),button=form.querySelector('button[type="submit"],button.btn'),parent_email=document.querySelector("#guardianEmail").value.trim();if(button)button.disabled=true;try{const response=await fetch('/api/parent-setup-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parent_email})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to save the setup request right now.');msg.innerHTML=`<div class="success"><strong>You're all set for now.</strong><br>Your parent or guardian can complete the family setup.</div>`;form.reset()}catch(error){msg.innerHTML=`<div class="error">${esc(error.message)}</div>`}finally{if(button)button.disabled=false}}}
function teenSignup(age){shell(`<div class="eyebrow">STUDENT ACCOUNT</div><h1>Create your learner account</h1><p class="muted">You can start independently. When Premium access is needed, we'll make it easy to invite a parent or guardian to manage billing.</p><div id="msg"></div><form id="teenForm"><div class="field"><label>First name</label><input id="sFirst" required></div><div class="field"><label>Last name</label><input id="sLast" required></div><div class="field"><label>Date of birth</label><input id="sDob" type="date" required></div><div class="field"><label>Email</label><input id="sEmail" type="email" required></div><div class="field"><label>Password</label><input id="sPass" type="password" minlength="8" required></div><button class="btn">Create student account</button></form><button class="linkbtn" id="backAge">← Back</button>`);document.querySelector("#backAge").onclick=studentAge;document.querySelector("#teenForm").onsubmit=async e=>{e.preventDefault();const{data,error}=await supabase.auth.signUp({email:document.querySelector("#sEmail").value.trim(),password:document.querySelector("#sPass").value,options:{data:{role:"student",first_name:document.querySelector("#sFirst").value.trim(),last_name:document.querySelector("#sLast").value.trim(),date_of_birth:document.querySelector("#sDob").value,age_at_signup:String(age)}}});if(error)return document.querySelector("#msg").innerHTML=`<div class="error">${esc(error.message)}</div>`;if(data.session)location.assign("/?app=1");else document.querySelector("#msg").innerHTML=`<div class="success">Check your email to confirm your account, then log in.</div>`}}
async function init(){
 const params=new URLSearchParams(location.search);
 if(params.get("app")==="1"||params.get("billing")==="success")return;
 // Public content must never depend on auth bootstrap completing.
 renderHome();
 if(!supabase)return;
 try{
  const result=await Promise.race([
   supabase.auth.getSession(),
   new Promise(resolve=>setTimeout(()=>resolve({data:{session:null}}),1500))
  ]);
  const nextSession=result?.data?.session||null;
  if(nextSession!==activeSession){activeSession=nextSession;renderHome()}
 }catch{
  // Keep the public homepage usable when auth initialization is unavailable.
 }
}
init();
