import './style.css';
import {supabase,configured} from './supabase.js';

const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const pct=x=>`${Math.round((Number(x)||0)*100)}%`;
let state=null,busy=false;

function top(){return `<div class="top"><div class="logo">SAT<span>prep.io</span> <span class="badge warn">PILOT CONTROL</span></div><div class="navlinks"><a class="linkbtn" href="/test-lab.html">Test Lab</a><a class="linkbtn" href="/?app=1">Admin</a><button class="linkbtn" id="signoutBtn">Sign out</button></div></div>`}
function bindTop(){document.querySelector('#signoutBtn')?.addEventListener('click',async()=>{await supabase.auth.signOut();location.assign('/')})}
async function authPost(url,body={}){const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Please sign in again.');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed.');return data}
function shell(body){app.innerHTML=top()+`<main class="wrap">${body}</main>`;bindTop()}
function metric(label,value,detail=''){return `<div class="card c3"><div class="label">${esc(label)}</div><div class="metric">${esc(value)}</div>${detail?`<div class="small">${esc(detail)}</div>`:''}</div>`}
function practiceText(rows){if(!rows?.length)return 'No targeted practice recorded';return rows.map(x=>`${x.skill}: ${Math.round(Number(x.score||0)*100)}%`).join(' · ')}
function runCard(run){const s=run.student||{},d=run.diagnostic||{};return `<article class="card" style="margin-bottom:14px"><div class="row"><div><div class="eyebrow">${esc(s.persona||'pilot')}</div><h2 style="margin:4px 0">${esc(s.display_name||'Deleted pilot student')}</h2><div class="small">${esc(run.label||'')} · ${esc(s.target_exam||'—')} · target ${esc(s.target_score||'—')}</div></div><span class="badge ${run.status==='completed'?'good':'warn'}">${esc(run.status)}</span></div><div class="grid" style="margin-top:14px"><div class="c3"><div class="label">R&W</div><strong>${d.rw_mastery==null?'—':pct(d.rw_mastery)}</strong></div><div class="c3"><div class="label">Math</div><strong>${d.math_mastery==null?'—':pct(d.math_mastery)}</strong></div><div class="c3"><div class="label">Overall</div><strong>${d.overall==null?'—':pct(d.overall)}</strong></div><div class="c3"><div class="label">Practice</div><strong>${run.practice?.length||0} sessions</strong></div></div><div class="small" style="margin-top:12px"><strong>Priority skills:</strong> ${(s.priority_skills||[]).map(x=>esc(x.skill||x)).join(', ')||'—'}<br><strong>Practice:</strong> ${esc(practiceText(run.practice))}</div><div class="row" style="margin-top:14px"><span class="small">Run ${esc(run.id)}</span>${s.id?`<button class="btn secondary" data-delete-student="${esc(s.id)}">Remove synthetic family</button>`:''}</div></article>`}
function render(message=''){
 if(!state)return shell(`<section class="hero"><h1>Pilot Agent Control Center</h1><p>Loading synthetic pilot operations…</p></section>`);
 shell(`<section class="hero"><div class="eyebrow">CLOSED PILOT READINESS</div><h1>Autonomous synthetic family testing</h1><p>Create unmistakably synthetic parent/student accounts, verify authentication, simulate a balanced diagnostic, and run targeted practice without enabling billing or promoting unreviewed commercial content.</p></section>${message?`<div class="success">${esc(message)}</div>`:''}<section class="grid">${metric('Pilot runs',state.counts.pilot_runs)}${metric('Completed',state.counts.completed)}${metric('Synthetic students',state.counts.test_students)}${metric('Synthetic households',state.counts.test_households)}</section><section class="card" style="margin-top:18px"><div class="row"><div><h2>Launch a pilot agent</h2><div class="small">Each run creates its own parent, household and student test identity.</div></div><button class="btn secondary" id="refreshPilot">Refresh</button></div><div class="grid" style="margin-top:12px">${state.personas.map(p=>`<div class="card c4" style="box-shadow:none"><strong>${esc(p.label)}</strong><div class="small">Grade ${p.grade} · ${esc(p.target_exam)} · target ${p.target_score}</div><button class="btn" data-persona="${esc(p.key)}" style="margin-top:10px" ${busy?'disabled':''}>Run agent</button></div>`).join('')}</div><div id="pilotMessage"></div></section><section style="margin-top:18px"><div class="row"><h2>Recent pilot runs</h2><span class="badge">${state.runs.length} shown</span></div>${state.runs.length?state.runs.map(runCard).join(''):'<div class="card"><p>No pilot-agent runs yet.</p></div>'}</section>`);
 document.querySelector('#refreshPilot').onclick=load;
 document.querySelectorAll('[data-persona]').forEach(b=>b.onclick=()=>runAgent(b.dataset.persona));
 document.querySelectorAll('[data-delete-student]').forEach(b=>b.onclick=()=>removeFamily(b.dataset.deleteStudent));
}
async function load(){try{state=await authPost('/api/pilot-agent-overview');render()}catch(e){shell(`<section class="card"><h1>Pilot Agent Control Center</h1><div class="error">${esc(e.message)}</div></section>`)}}
async function runAgent(persona){if(busy)return;busy=true;render();const msg=document.querySelector('#pilotMessage');if(msg)msg.innerHTML='<div class="notice" style="margin-top:12px">Running synthetic family journey…</div>';try{const result=await authPost('/api/pilot-agent-run',{persona});busy=false;await load();render(`${result.persona_label} completed: parent/student auth verified, ${result.diagnostic.total} diagnostic questions, and ${result.practice.length} targeted practice sessions.`)}catch(e){busy=false;render();const next=document.querySelector('#pilotMessage');if(next)next.innerHTML=`<div class="error" style="margin-top:12px">${esc(e.message)}</div>`}}
async function removeFamily(studentId){if(busy)return;busy=true;try{await authPost('/api/pilot-agent-delete',{student_id:studentId});busy=false;await load();render('Synthetic pilot family removed. Historical test-run telemetry was retained.')}catch(e){busy=false;render();const msg=document.querySelector('#pilotMessage');if(msg)msg.innerHTML=`<div class="error" style="margin-top:12px">${esc(e.message)}</div>`}}
async function boot(){if(!configured)return shell('<section class="card"><h1>Pilot Agent Control Center</h1><div class="error">Supabase is not configured.</div></section>');const{data:{session}}=await supabase.auth.getSession();if(!session){location.assign('/');return}const{data:profile}=await supabase.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(profile?.role!=='admin')return shell('<section class="card"><h1>Pilot Agent Control Center</h1><div class="error">Administrator access is required.</div></section>');await load()}
boot();
