import {SKILL_INDEX} from './sat-spec.js';

const p=x=>({version:1,status:'internal_review',origin:'satprep_original_practice',format:'mcq',...x});
export const PRACTICE_BANK=[
 p({id:'p-rw-001',section:'RW',domain:'information-and-ideas',skill:'central-ideas-details',difficulty:1,stimulus:'A middle school installed soil sensors in its garden to measure moisture. Students expected the sensors mainly to help decide when to water. After several months, they also used the data to compare how quickly different garden beds dried after rain. The project therefore became both a maintenance tool and a source of data for science lessons.',stem:'Which choice best states the main idea of the text?',choices:['The soil sensors became useful for both caring for the garden and studying it.','Students stopped watering the garden after installing sensors.','Rainfall was the only topic studied in science lessons.','The school installed sensors because the garden beds were identical.'],answerIndex:0,explanation:'The passage describes two uses that developed from the sensor project: garden maintenance and scientific investigation.'}),
 p({id:'p-rw-002',section:'RW',domain:'information-and-ideas',skill:'command-evidence-textual',difficulty:2,stimulus:'A park tested two walking-trail surfaces during a rainy season. The gravel trail developed several deep ruts and required three repairs. The compacted-stone trail developed only one shallow rut and required no repairs during the same period.',stem:'Which detail most directly supports the claim that the compacted-stone surface required less maintenance?',choices:['The test occurred during a rainy season.','The gravel trail developed deep ruts.','The compacted-stone trail required no repairs while the gravel trail required three.','Both trails were used for walking.'],answerIndex:2,explanation:'The claim is specifically about maintenance, so the direct comparison of repair needs is the strongest evidence.'}),
 p({id:'p-rw-003',section:'RW',domain:'information-and-ideas',skill:'command-evidence-quantitative',difficulty:2,stimulus:'Workshop attendance — Monday: 34; Tuesday: 41; Wednesday: 39; Thursday: 52.',stem:'Which statement is supported by the data?',choices:['Attendance increased every day.','Thursday had the highest attendance.','Monday and Wednesday had equal attendance.','Tuesday had fewer attendees than Monday.'],answerIndex:1,explanation:'Thursday had 52 attendees, which is more than the attendance on Monday, Tuesday, or Wednesday.'}),
 p({id:'p-rw-004',section:'RW',domain:'information-and-ideas',skill:'inferences',difficulty:2,stimulus:'Before presenting her design, Aisha tested the model twice, packed replacement batteries, and saved a backup copy of her slides on a second device.',stem:'Which inference is best supported?',choices:['Aisha expects the presentation to be canceled.','Aisha is taking steps to prepare for possible technical problems.','Aisha has never used the model before.','Aisha plans to give two presentations at once.'],answerIndex:1,explanation:'Testing the model, bringing backup power, and saving a second copy all show preparation for possible technical failures.'}),
 p({id:'p-rw-005',section:'RW',domain:'craft-and-structure',skill:'words-in-context',difficulty:2,stimulus:'The reviewer offered a qualified endorsement of the proposal, praising its goals while noting that its cost estimates needed more evidence.',stem:'As used in the text, “qualified” most nearly means',choices:['limited by reservations','professionally certified','completely enthusiastic','difficult to understand'],answerIndex:0,explanation:'The reviewer supports the proposal but also expresses reservations, so the endorsement is limited or conditional.'}),
 p({id:'p-rw-006',section:'RW',domain:'craft-and-structure',skill:'text-structure-purpose',difficulty:2,stimulus:'Early bicycle helmets were often heavy and poorly ventilated. Newer materials allowed manufacturers to reduce weight while maintaining impact protection. Modern designs also include channels that improve airflow around a rider’s head.',stem:'What is the main purpose of the second sentence?',choices:['To introduce one way newer technology addressed a limitation of earlier helmets','To argue that early helmets provided no protection','To explain why bicycles became lighter','To list every material used in modern helmets'],answerIndex:0,explanation:'The second sentence explains how newer materials improved on a specific weakness identified in the first sentence: excess weight.'}),
 p({id:'p-rw-007',section:'RW',domain:'craft-and-structure',skill:'cross-text-connections',difficulty:3,stimulus:'Text 1: Researcher Kim argues that school libraries should increase digital-book collections because students can access them outside school hours. Text 2: Researcher Patel agrees that digital access is valuable but argues that print collections should remain strong because some students read longer texts more comfortably on paper.',stem:'How would Patel most likely respond to Kim?',choices:['By agreeing about the value of digital access while arguing for a balanced collection','By claiming digital books cannot be accessed outside school','By arguing that libraries should stop buying books entirely','By denying that students have different reading preferences'],answerIndex:0,explanation:'Patel shares Kim’s positive view of digital access but adds a reason to preserve print resources as well.'}),
 p({id:'p-rw-008',section:'RW',domain:'expression-of-ideas',skill:'rhetorical-synthesis',difficulty:2,stimulus:'Notes: Architect Mina Torres designed a community center. The roof collects rainwater. Collected water is used to irrigate the landscaping. A student wants to emphasize how the design reduces demand for treated water.',stem:'Which choice best accomplishes the student’s goal?',choices:['Mina Torres designed a community center with landscaping.','The center’s roof collects rainwater that is reused for irrigation, reducing the need to use treated water on the landscaping.','Rainwater falls on many kinds of roofs.','Torres designed both the roof and the community center.'],answerIndex:1,explanation:'The choice selects the two relevant facts—rainwater collection and irrigation reuse—and directly connects them to reduced treated-water demand.'}),
 p({id:'p-rw-009',section:'RW',domain:'expression-of-ideas',skill:'transitions',difficulty:1,stimulus:'The first survey reached only 40 participants. _____, the researchers conducted a second survey with more than 500 participants.',stem:'Which transition most logically completes the text?',choices:['For example','Consequently','Likewise','Meanwhile'],answerIndex:1,explanation:'The larger second survey was conducted as a result of the first survey’s limited reach, so “Consequently” fits.'}),
 p({id:'p-rw-010',section:'RW',domain:'standard-english-conventions',skill:'boundaries',difficulty:2,stimulus:'The lab uses three renewable energy sources _____ solar panels, a small wind turbine, and geothermal heating.',stem:'Which choice completes the sentence correctly?',choices:[',',':',';','and:'],answerIndex:1,explanation:'A complete clause introduces a list, so a colon correctly separates the clause from the examples.'}),
 p({id:'p-rw-011',section:'RW',domain:'standard-english-conventions',skill:'form-structure-sense',difficulty:2,stimulus:'The set of revised maps _____ stored in the archive’s climate-controlled room.',stem:'Which choice completes the sentence correctly?',choices:['are','is','have','were being and is'],answerIndex:1,explanation:'The grammatical subject is the singular noun “set,” so the singular verb “is” is required.'}),

 p({id:'p-m-001',section:'MATH',domain:'algebra',skill:'linear-equations-one-variable',difficulty:1,stem:'Solve 5x+8=43.',choices:['5','7','8','10'],answerIndex:1,explanation:'Subtract 8 from both sides to get 5x=35, then divide by 5. The correct answer is x=7.'}),
 p({id:'p-m-002',section:'MATH',domain:'algebra',skill:'linear-functions',difficulty:2,stem:'A linear function passes through (1,4) and (5,20). What is the function’s value when x=8?',choices:['24','28','32','40'],answerIndex:2,explanation:'The slope is (20−4)/(5−1)=4. The line is y=4x, so at x=8 the value is 32.'}),
 p({id:'p-m-003',section:'MATH',domain:'algebra',skill:'linear-equations-two-variables',difficulty:2,stem:'The point (4,y) lies on 4x−y=13. What is y?',choices:['1','3','13','29'],answerIndex:1,explanation:'Substitute x=4: 16−y=13. Subtract 13 to get 3−y=0, so y=3.'}),
 p({id:'p-m-004',section:'MATH',domain:'algebra',skill:'systems-linear-equations',difficulty:2,stem:'If y=x+7 and y=3x−1, what is x?',choices:['2','4','6','8'],answerIndex:1,explanation:'Set the expressions equal: x+7=3x−1. Add 1 and subtract x to get 8=2x, so x=4.'}),
 p({id:'p-m-005',section:'MATH',domain:'algebra',skill:'linear-inequalities',difficulty:2,stem:'Which inequality is equivalent to 2x+9<19?',choices:['x<5','x>5','x<14','x>14'],answerIndex:0,explanation:'Subtract 9 to get 2x<10, then divide by 2. The solution is x<5.'}),
 p({id:'p-m-006',section:'MATH',domain:'advanced-math',skill:'equivalent-expressions',difficulty:1,stem:'Which expression is equivalent to 2(x+3)+5x?',choices:['7x+3','7x+6','10x+6','5x+6'],answerIndex:1,explanation:'Distribute 2 to get 2x+6, then combine 2x+5x. The result is 7x+6.'}),
 p({id:'p-m-007',section:'MATH',domain:'advanced-math',skill:'nonlinear-equations-one-variable',difficulty:2,stem:'What are the solutions to x²−10x+21=0?',choices:['3 and 7','−3 and −7','1 and 21','−1 and −21'],answerIndex:0,explanation:'Factor the quadratic as (x−3)(x−7)=0, giving x=3 and x=7.'}),
 p({id:'p-m-008',section:'MATH',domain:'advanced-math',skill:'systems-equations-two-variables',difficulty:3,stem:'The graphs y=x² and y=5x−6 intersect at two points. What is the sum of their x-coordinates?',choices:['2','3','5','6'],answerIndex:2,explanation:'Set x²=5x−6, so x²−5x+6=0=(x−2)(x−3). The x-values are 2 and 3, whose sum is 5.'}),
 p({id:'p-m-009',section:'MATH',domain:'advanced-math',skill:'nonlinear-functions',difficulty:2,stem:'If f(x)=(x−2)²+1, what is f(5)?',choices:['6','9','10','16'],answerIndex:2,explanation:'Substitute 5: (5−2)²+1=3²+1=10.'}),
 p({id:'p-m-010',section:'MATH',domain:'problem-solving-data-analysis',skill:'ratios-rates-units',difficulty:1,stem:'Three identical bottles hold a total of 24 ounces. How many ounces would seven such bottles hold?',choices:['42','48','56','72'],answerIndex:2,explanation:'Each bottle holds 24÷3=8 ounces. Seven bottles hold 7×8=56 ounces.'}),
 p({id:'p-m-011',section:'MATH',domain:'problem-solving-data-analysis',skill:'percentages',difficulty:1,stem:'A value of 80 is decreased by 25%. What is the new value?',choices:['20','55','60','75'],answerIndex:2,explanation:'A 25% decrease means 75% remains. 80×0.75=60.'}),
 p({id:'p-m-012',section:'MATH',domain:'problem-solving-data-analysis',skill:'one-variable-data',difficulty:2,stem:'The mean of 5, 7, 8, and x is 8. What is x?',choices:['10','11','12','13'],answerIndex:2,explanation:'Four numbers with mean 8 have total 32. The known values total 20, so x=32−20=12.'}),
 p({id:'p-m-013',section:'MATH',domain:'problem-solving-data-analysis',skill:'two-variable-data',difficulty:2,stem:'A model for a data set is y=2.5x+6. What value of y does the model predict when x=8?',choices:['14','20','26','32'],answerIndex:2,explanation:'Substitute x=8: y=2.5(8)+6=20+6=26.'}),
 p({id:'p-m-014',section:'MATH',domain:'problem-solving-data-analysis',skill:'probability',difficulty:2,stem:'A jar contains 6 red and 4 blue beads. A bead is selected at random. Given that the bead is not red, what is the probability that it is blue?',choices:['2/5','3/5','1','4/10'],answerIndex:2,explanation:'If the bead is known not to be red, only the 4 blue beads remain possible. Therefore the conditional probability is 1.'}),
 p({id:'p-m-015',section:'MATH',domain:'problem-solving-data-analysis',skill:'sample-statistics',difficulty:2,stem:'A random sample of 150 customers at one grocery store has an average checkout time of 6.4 minutes. Which population can the sample most reasonably be used to estimate?',choices:['All shoppers in the country','Customers at that grocery store','All retail workers','Only the 150 sampled customers and no one else'],answerIndex:1,explanation:'Because the sample was randomly drawn from customers at that store, it can support an estimate about the store’s customer population.'}),
 p({id:'p-m-016',section:'MATH',domain:'problem-solving-data-analysis',skill:'statistical-claims',difficulty:3,exams:['SAT'],stem:'Participants were randomly assigned to use either a standard training program or a new training program. The new-program group improved more on a later skills test. What feature is most important for supporting a causal conclusion?',choices:['The skills test had many questions.','The participants were randomly assigned.','The study compared two averages.','The new program had a longer name.'],answerIndex:1,explanation:'Random assignment helps balance other factors between the groups, making the program itself a plausible cause of the outcome difference.'}),
 p({id:'p-m-017',section:'MATH',domain:'geometry-trigonometry',skill:'area-volume',difficulty:2,stem:'A prism has a base area of 12 square units and a height of 5 units. What is its volume?',choices:['17','30','60','120'],answerIndex:2,explanation:'Prism volume equals base area times height: 12×5=60 cubic units.'}),
 p({id:'p-m-018',section:'MATH',domain:'geometry-trigonometry',skill:'lines-angles-triangles',difficulty:1,stem:'Two angles in a triangle measure 35° and 85°. What is the third angle?',choices:['50°','60°','70°','120°'],answerIndex:1,explanation:'The angles of a triangle sum to 180°. 180−35−85=60°.'}),
 p({id:'p-m-019',section:'MATH',domain:'geometry-trigonometry',skill:'right-triangles-trigonometry',difficulty:2,stem:'In a right triangle, an acute angle θ has opposite side 5 and adjacent side 12. What is tan θ?',choices:['5/12','12/5','5/13','12/13'],answerIndex:0,explanation:'Tangent is opposite divided by adjacent, so tan θ=5/12.'}),
 p({id:'p-m-020',section:'MATH',domain:'geometry-trigonometry',skill:'circles',difficulty:2,exams:['SAT'],stem:'A circle has diameter 14. What is its circumference?',choices:['7π','14π','28π','196π'],answerIndex:1,explanation:'Circumference can be found with C=πd. With diameter 14, C=14π.'})
];

export function practiceForSkill(skill,targetExam='SAT'){return PRACTICE_BANK.filter(q=>q.skill===skill&&(!q.exams||q.exams.includes(targetExam)))}
export function validatePracticeBank(){const errors=[],ids=new Set();for(const q of PRACTICE_BANK){if(ids.has(q.id))errors.push(`Duplicate practice id ${q.id}`);ids.add(q.id);if(!SKILL_INDEX[q.skill])errors.push(`${q.id}: unknown skill ${q.skill}`);if(!Array.isArray(q.choices)||q.choices.length!==4)errors.push(`${q.id}: four choices required`);if(!Number.isInteger(q.answerIndex)||q.answerIndex<0||q.answerIndex>3)errors.push(`${q.id}: invalid answer`);if(!q.explanation)errors.push(`${q.id}: explanation required`)}return errors}
