import {SKILL_INDEX,skillEligibleForExam} from './sat-spec.js';

// SATprep.io ORIGINAL CONTENT ONLY.
// These items were authored for SATprep.io and are not transcriptions or close paraphrases of College Board items.
// status='internal_review' means structurally/answer-key reviewed but not yet cleared by the independent production QA gate.
const base={version:1,status:'internal_review',origin:'satprep_original'};
const mc=(x)=>({...base,format:'mcq',estimatedSeconds:x.section==='RW'?75:95,...x});

export const QUESTION_BANK=[
 mc({id:'rw-iid-001',section:'RW',domain:'information-and-ideas',skill:'central-ideas-details',difficulty:1,stimulus:{type:'text',text:'A city library began lending small tool kits containing items such as screwdrivers, levels, and measuring tapes. Staff members initially expected the kits to appeal mainly to homeowners. Instead, many borrowers were apartment residents who used the tools for small repairs, furniture assembly, and community projects. The library later expanded the collection after reservations regularly exceeded supply.'},stem:'Which choice best states the main idea of the text?',choices:['The library stopped lending books so that it could lend tools.','The tool-lending program served a broader group of residents than staff first expected.','Apartment residents generally own more tools than homeowners do.','Community projects were the only reason residents borrowed the tool kits.'],answerIndex:1,explanation:'The passage emphasizes that staff expected one main audience but discovered that many apartment residents also used the kits, leading the library to expand the program.'}),
 mc({id:'rw-iid-002',section:'RW',domain:'information-and-ideas',skill:'command-evidence-textual',difficulty:2,stimulus:{type:'text',text:'Biologist Amara Chen studied two populations of the same coastal plant. Plants growing close to the shoreline were shorter than plants farther inland. Chen found that the shoreline plants were exposed to stronger winds but received nearly the same amount of sunlight and water as the inland plants.'},stem:'Which finding from the text most directly supports the claim that wind exposure may be related to plant height?',choices:['The two groups were the same species.','The shoreline plants were shorter and experienced stronger winds.','Both groups received nearly the same amount of water.','The inland plants grew farther from the ocean.'],answerIndex:1,explanation:'The relevant comparison links the two variables in the claim: stronger wind exposure and shorter plant height.'}),
 mc({id:'rw-iid-003',section:'RW',domain:'information-and-ideas',skill:'command-evidence-quantitative',difficulty:2,stimulus:{type:'table',title:'Average weekly visits to a community garden',columns:['Month','Morning','Evening'],rows:[['April','42','31'],['May','47','39'],['June','45','58']]},stem:'Which statement is best supported by the table?',choices:['Morning visits increased every month.','Evening visits were highest in June.','Total visits were lowest in June.','Evening visits exceeded morning visits in every month.'],answerIndex:1,explanation:'June has 58 evening visits, more than May’s 39 and April’s 31. The other statements are contradicted by the table.'}),
 mc({id:'rw-iid-004',section:'RW',domain:'information-and-ideas',skill:'inferences',difficulty:2,stimulus:{type:'text',text:'When the museum announced that its new exhibit would open at noon, Luis arrived at 11:30. He checked the floor map while waiting and marked two galleries on his phone. As soon as the doors opened, he walked directly toward the first marked gallery.'},stem:'Which inference is best supported by the text?',choices:['Luis had visited every gallery before.','Luis planned in advance which parts of the exhibit he wanted to see.','Luis was employed by the museum.','Luis intended to leave before noon.'],answerIndex:1,explanation:'Luis arrived early, consulted a map, marked galleries, and headed directly to one of them. Those details support advance planning.'}),
 mc({id:'rw-cs-001',section:'RW',domain:'craft-and-structure',skill:'words-in-context',difficulty:1,stimulus:{type:'text',text:'The researcher described the early results as preliminary and cautioned that a larger study might produce a different conclusion.'},stem:'As used in the text, “preliminary” most nearly means',choices:['final and certain','occurring before fuller evidence is available','unrelated to the research question','difficult to calculate'],answerIndex:1,explanation:'The warning that a larger study could change the conclusion shows that the results are early rather than final.'}),
 mc({id:'rw-cs-002',section:'RW',domain:'craft-and-structure',skill:'text-structure-purpose',difficulty:2,stimulus:{type:'text',text:'For decades, astronomers estimated the age of a star cluster by comparing the brightness of its stars. A newer method instead measures subtle changes in how certain stars vibrate. Researchers now compare results from both techniques to identify cases in which one method may be less reliable.'},stem:'Which choice best describes the function of the second sentence in the overall structure of the text?',choices:['It presents a newer approach after the text introduces an older one.','It gives an example proving that all older estimates were wrong.','It defines why stars form clusters.','It argues that brightness cannot be measured accurately.'],answerIndex:0,explanation:'The first sentence describes the traditional method; the second introduces a newer, contrasting method.'}),
 mc({id:'rw-cs-003',section:'RW',domain:'craft-and-structure',skill:'cross-text-connections',difficulty:3,stimulus:{type:'paired',textA:'Historian Dana Ortiz argues that early public parks were designed mainly to provide crowded cities with open space and fresh air.',textB:'Historian Marcus Lee agrees that health concerns influenced park design but emphasizes another goal: planners also intended parks to create shared spaces where residents from different neighborhoods could gather.'},stem:'Based on the texts, Ortiz and Lee would most likely agree that early public parks',choices:['were designed for only one purpose','were influenced at least partly by concerns about urban living conditions','were used mostly by residents from wealthy neighborhoods','eliminated health problems in crowded cities'],answerIndex:1,explanation:'Both texts connect park design to conditions in crowded cities; Lee simply adds another purpose.'}),
 mc({id:'rw-eoi-001',section:'RW',domain:'expression-of-ideas',skill:'rhetorical-synthesis',difficulty:2,stimulus:{type:'notes',items:['Engineer Priya Shah designed a low-cost water sensor.','The sensor can detect leaks in household pipes.','It sends an alert to a phone when unusual water flow is detected.','A student wants to emphasize the sensor’s practical benefit to homeowners.']},stem:'Which choice most effectively uses relevant information from the notes to accomplish the student’s goal?',choices:['Priya Shah is an engineer who designed a sensor.','The low-cost sensor can alert homeowners to unusual water flow, helping them identify possible leaks.','Household pipes carry water, and some engineers study them.','The sensor sends information to a phone, and Shah designed it.'],answerIndex:1,explanation:'The choice combines the leak-detection and alert features and directly explains why those features are useful to homeowners.'}),
 mc({id:'rw-eoi-002',section:'RW',domain:'expression-of-ideas',skill:'transitions',difficulty:1,stimulus:{type:'text',text:'The first prototype was too heavy for field use. _____, the design team replaced several steel components with aluminum ones.'},stem:'Which choice completes the text with the most logical transition?',choices:['For example','As a result','Meanwhile','In contrast'],answerIndex:1,explanation:'Replacing the components happened because the prototype was too heavy, so “As a result” expresses the cause-and-effect relationship.'}),
 mc({id:'rw-sec-001',section:'RW',domain:'standard-english-conventions',skill:'boundaries',difficulty:2,stimulus:{type:'text',text:'The research team collected three kinds of samples _____ soil, pond water, and tree bark.'},stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',choices:[',',':',';','— and'],answerIndex:1,explanation:'The words before the blank form a complete clause, and the words after it are a list introduced by that clause. A colon is appropriate.'}),
 mc({id:'rw-sec-002',section:'RW',domain:'standard-english-conventions',skill:'form-structure-sense',difficulty:2,stimulus:{type:'text',text:'The collection of historic photographs, along with several handwritten letters, _____ stored in a climate-controlled room.'},stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',choices:['are','were','is','have been'],answerIndex:2,explanation:'The subject is the singular noun “collection.” The intervening phrases do not change the subject, so the singular verb “is” is required.'}),

 mc({id:'m-alg-001',section:'MATH',domain:'algebra',skill:'linear-equations-one-variable',difficulty:1,stem:'If 7x − 9 = 40, what is the value of x?',choices:['5','7','8','31'],answerIndex:1,explanation:'Add 9 to both sides to get 7x = 49, then divide by 7. Thus x = 7.'}),
 mc({id:'m-alg-002',section:'MATH',domain:'algebra',skill:'linear-functions',difficulty:2,stem:'A linear function f satisfies f(2)=11 and f(6)=23. What is f(10)?',choices:['29','31','35','47'],answerIndex:2,explanation:'The slope is (23−11)/(6−2)=3. Increasing x from 6 to 10 increases f(x) by 3×4=12, so f(10)=35.'}),
 mc({id:'m-alg-003',section:'MATH',domain:'algebra',skill:'linear-equations-two-variables',difficulty:2,stem:'The point (4, k) lies on the line 3x + 2y = 26. What is the value of k?',choices:['5','7','9','14'],answerIndex:1,explanation:'Substitute x=4: 12+2k=26. Then 2k=14, so k=7.'}),
 mc({id:'m-alg-004',section:'MATH',domain:'algebra',skill:'systems-linear-equations',difficulty:2,stem:'What is the x-coordinate of the solution to the system y=2x+3 and y=−x+12?',choices:['2','3','5','9'],answerIndex:1,explanation:'Set the two expressions for y equal: 2x+3=−x+12. Then 3x=9, so x=3.'}),
 mc({id:'m-alg-005',section:'MATH',domain:'algebra',skill:'linear-inequalities',difficulty:2,stem:'Which value of x satisfies 5x − 4 > 21?',choices:['4','5','5.1','−6'],answerIndex:2,explanation:'Add 4 to get 5x>25, then divide by 5 to get x>5. Of the choices, only 5.1 is greater than 5.'}),
 mc({id:'m-adv-001',section:'MATH',domain:'advanced-math',skill:'equivalent-expressions',difficulty:2,stem:'Which expression is equivalent to (x+4)(x−2)?',choices:['x²+2x−8','x²−2x−8','x²+6x−8','x²+2x+8'],answerIndex:0,explanation:'Multiply: x²−2x+4x−8=x²+2x−8.'}),
 mc({id:'m-adv-002',section:'MATH',domain:'advanced-math',skill:'nonlinear-equations-one-variable',difficulty:2,stem:'What are the solutions to x² − 5x − 14 = 0?',choices:['−7 and 2','−2 and 7','2 and 7','−1 and 14'],answerIndex:1,explanation:'Factor as (x−7)(x+2)=0, giving x=7 or x=−2.'}),
 mc({id:'m-adv-003',section:'MATH',domain:'advanced-math',skill:'systems-equations-two-variables',difficulty:3,stem:'The graphs of y=x² and y=3x+4 intersect at two points. What is the sum of the x-coordinates of those points?',choices:['−4','−3','3','4'],answerIndex:2,explanation:'Set x²=3x+4, so x²−3x−4=0=(x−4)(x+1). The x-values are 4 and −1, whose sum is 3.'}),
 mc({id:'m-adv-004',section:'MATH',domain:'advanced-math',skill:'nonlinear-functions',difficulty:2,stem:'For the function g(x)=2(3^x), what is the value of g(2)?',choices:['6','12','18','36'],answerIndex:2,explanation:'Substitute x=2: g(2)=2(3²)=2(9)=18.'}),
 mc({id:'m-psda-001',section:'MATH',domain:'problem-solving-data-analysis',skill:'ratios-rates-units',difficulty:1,stem:'A printer produces 180 pages in 6 minutes at a constant rate. At that rate, how many pages does it produce in 15 minutes?',choices:['360','420','450','540'],answerIndex:2,explanation:'The rate is 180÷6=30 pages per minute. In 15 minutes it produces 30×15=450 pages.'}),
 mc({id:'m-psda-002',section:'MATH',domain:'problem-solving-data-analysis',skill:'percentages',difficulty:2,stem:'A quantity increases from 240 to 300. What is the percent increase?',choices:['20%','25%','60%','80%'],answerIndex:1,explanation:'The increase is 60. Divide by the original amount: 60÷240=0.25=25%.'}),
 mc({id:'m-psda-003',section:'MATH',domain:'problem-solving-data-analysis',skill:'one-variable-data',difficulty:2,stem:'The data set is 4, 6, 6, 8, 11. If 16 is added to the data set, which measure must increase?',choices:['Median only','Mean only','Both mean and median','Neither mean nor median'],answerIndex:1,explanation:'The original mean is 7 and becomes 8.5 after adding 16, so it increases. The median remains 6 because the ordered set becomes 4,6,6,8,11,16.'}),
 mc({id:'m-psda-004',section:'MATH',domain:'problem-solving-data-analysis',skill:'two-variable-data',difficulty:2,stimulus:{type:'text',text:'A scatterplot of weekly practice time and typing speed shows points clustered around an upward-sloping line. The points are fairly close to the line, though not all lie exactly on it.'},stem:'Which statement best describes the relationship shown?',choices:['A strong positive association','A strong negative association','No association','A perfect negative association'],answerIndex:0,explanation:'As practice time increases, typing speed tends to increase, and the points lie fairly close to an upward trend. That indicates a strong positive association.'}),
 mc({id:'m-psda-005',section:'MATH',domain:'problem-solving-data-analysis',skill:'probability',difficulty:2,stem:'A bag contains 5 red, 3 blue, and 2 green tiles. One tile is selected at random. Given that the selected tile is not green, what is the probability that it is blue?',choices:['3/10','3/8','5/8','7/10'],answerIndex:1,explanation:'Conditioning on “not green” leaves 8 possible tiles: 5 red and 3 blue. Of those 8, 3 are blue, so the probability is 3/8.'}),
 mc({id:'m-psda-006',section:'MATH',domain:'problem-solving-data-analysis',skill:'sample-statistics',difficulty:3,stem:'A random sample of 200 students at a large high school has an average commute time of 18 minutes. Which conclusion is most appropriate?',choices:['Every student at the school commutes exactly 18 minutes.','The sample mean can be used to estimate the average commute time for students at the school.','The average commute time for all teenagers is exactly 18 minutes.','The sample proves that longer commutes cause lower grades.'],answerIndex:1,explanation:'Because the students were randomly sampled from that school, the sample mean can be used to estimate the school population mean. The result does not apply automatically to all teenagers and does not establish causation.'}),
 mc({id:'m-psda-007',section:'MATH',domain:'problem-solving-data-analysis',skill:'statistical-claims',difficulty:3,exams:['SAT'],stem:'Researchers randomly assigned volunteers to use either a new study method or their usual method for four weeks. The new-method group later had a higher average quiz score. Which feature most directly supports a causal conclusion about the study method?',choices:['The study lasted four weeks.','The volunteers took quizzes.','Participants were randomly assigned to groups.','The new-method group had more participants.'],answerIndex:2,explanation:'Random assignment helps make the groups comparable before treatment, allowing differences in outcomes to support a causal conclusion.'}),
 mc({id:'m-geo-001',section:'MATH',domain:'geometry-trigonometry',skill:'area-volume',difficulty:1,stem:'A rectangular prism has length 8, width 5, and height 3. What is its volume?',choices:['16','40','80','120'],answerIndex:3,explanation:'Volume of a rectangular prism is length×width×height: 8×5×3=120.'}),
 mc({id:'m-geo-002',section:'MATH',domain:'geometry-trigonometry',skill:'lines-angles-triangles',difficulty:2,stem:'Two angles of a triangle measure 48° and 67°. What is the measure of the third angle?',choices:['55°','65°','75°','115°'],answerIndex:1,explanation:'Triangle angles sum to 180°. The third angle is 180−48−67=65°.'}),
 mc({id:'m-geo-003',section:'MATH',domain:'geometry-trigonometry',skill:'right-triangles-trigonometry',difficulty:2,stem:'In a right triangle, an acute angle θ has opposite side length 6 and hypotenuse length 10. What is sin θ?',choices:['3/5','4/5','5/3','5/4'],answerIndex:0,explanation:'For an acute angle in a right triangle, sin θ=opposite/hypotenuse=6/10=3/5.'}),
 mc({id:'m-geo-004',section:'MATH',domain:'geometry-trigonometry',skill:'circles',difficulty:2,exams:['SAT'],stem:'A circle has radius 9. What is its circumference?',choices:['9π','18π','81π','162π'],answerIndex:1,explanation:'Circumference is 2πr. With r=9, C=18π.'})
];

export function examsFor(item){return item.exams||['SAT','PSAT/NMSQT','PSAT 10']}
export function eligibleQuestions(targetExam){return QUESTION_BANK.filter(q=>examsFor(q).includes(targetExam)&&skillEligibleForExam(q.skill,targetExam))}
export function questionById(id){return QUESTION_BANK.find(q=>q.id===id)||null}

export function validateQuestionBank(){
 const errors=[],ids=new Set();
 for(const q of QUESTION_BANK){
  if(!q.id||ids.has(q.id))errors.push(`Duplicate or missing id: ${q.id}`);ids.add(q.id);
  const skill=SKILL_INDEX[q.skill];if(!skill)errors.push(`${q.id}: unknown skill ${q.skill}`);
  else if(skill.domainKey!==q.domain||skill.section!==q.section)errors.push(`${q.id}: section/domain does not match skill taxonomy`);
  if(!['RW','MATH'].includes(q.section))errors.push(`${q.id}: invalid section`);
  if(![1,2,3].includes(q.difficulty))errors.push(`${q.id}: difficulty must be 1, 2, or 3`);
  if(q.format==='mcq'){
   if(!Array.isArray(q.choices)||q.choices.length!==4)errors.push(`${q.id}: MCQ must have exactly four choices`);
   if(!Number.isInteger(q.answerIndex)||q.answerIndex<0||q.answerIndex>3)errors.push(`${q.id}: invalid answer index`);
  }
  if(q.origin!=='satprep_original')errors.push(`${q.id}: non-original origin is not allowed in the proprietary bank`);
  if(!q.explanation||q.explanation.length<20)errors.push(`${q.id}: explanation is required`);
  if(!q.status)errors.push(`${q.id}: QA status is required`);
  for(const exam of examsFor(q))if(!['SAT','PSAT/NMSQT','PSAT 10'].includes(exam))errors.push(`${q.id}: invalid exam eligibility ${exam}`);
 }
 return errors;
}
