-- SATprep.io initial production schema
-- Run in Supabase SQL Editor once for the project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  first_name text,
  role text not null default 'student' check (role in ('student','parent','admin','tutor')),
  created_at timestamptz not null default now()
);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid unique references public.profiles(id) on delete cascade,
  display_name text,
  grade_level integer,
  math_course text,
  target_exam text,
  target_score integer,
  target_date date,
  prior_testing_notes text,
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.parent_students (
  parent_profile_id uuid references public.profiles(id) on delete cascade,
  student_id uuid references public.students(id) on delete cascade,
  primary key (parent_profile_id, student_id)
);

create table if not exists public.lesson_progress (
  student_id uuid references public.students(id) on delete cascade,
  lesson_key text not null,
  current_question integer not null default 0,
  best_score numeric,
  last_score numeric,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (student_id, lesson_key)
);

create table if not exists public.skill_mastery (
  student_id uuid references public.students(id) on delete cascade,
  skill_key text not null,
  mastery numeric not null default 0,
  items_attempted integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (student_id, skill_key)
);

create table if not exists public.question_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students(id) on delete cascade,
  lesson_key text not null,
  question_index integer not null,
  skill_key text not null,
  selected_answer integer,
  correct_answer integer,
  is_correct boolean,
  response_ms integer,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  requested_role text;
  fname text;
begin
  requested_role := coalesce(new.raw_user_meta_data->>'role','student');
  if requested_role not in ('student','parent') then
    requested_role := 'student';
  end if;
  fname := coalesce(new.raw_user_meta_data->>'first_name','');

  insert into public.profiles(id,email,first_name,role)
  values(new.id,new.email,fname,requested_role);

  if requested_role='student' then
    insert into public.students(profile_id,display_name)
    values(new.id,fname);
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.students enable row level security;
alter table public.parent_students enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.skill_mastery enable row level security;
alter table public.question_attempts enable row level security;

-- Profiles: users can read/update their own profile.
create policy "profile_self_read" on public.profiles for select using (auth.uid() = id);
create policy "profile_self_update" on public.profiles for update using (auth.uid() = id);

-- Student row: student can read/update own record.
create policy "student_self_read" on public.students for select using (profile_id = auth.uid());
create policy "student_self_update" on public.students for update using (profile_id = auth.uid());

-- Parents may read linked student rows.
create policy "parent_linked_student_read" on public.students for select using (
  exists (
    select 1 from public.parent_students ps
    where ps.student_id = students.id and ps.parent_profile_id = auth.uid()
  )
);

-- Parent links visible to the parent involved.
create policy "parent_link_read" on public.parent_students for select using (parent_profile_id = auth.uid());

-- Student progress permissions.
create policy "lesson_student_all" on public.lesson_progress for all using (
  exists (select 1 from public.students s where s.id=lesson_progress.student_id and s.profile_id=auth.uid())
) with check (
  exists (select 1 from public.students s where s.id=lesson_progress.student_id and s.profile_id=auth.uid())
);
create policy "lesson_parent_read" on public.lesson_progress for select using (
  exists (select 1 from public.parent_students ps where ps.student_id=lesson_progress.student_id and ps.parent_profile_id=auth.uid())
);

create policy "skill_student_all" on public.skill_mastery for all using (
  exists (select 1 from public.students s where s.id=skill_mastery.student_id and s.profile_id=auth.uid())
) with check (
  exists (select 1 from public.students s where s.id=skill_mastery.student_id and s.profile_id=auth.uid())
);
create policy "skill_parent_read" on public.skill_mastery for select using (
  exists (select 1 from public.parent_students ps where ps.student_id=skill_mastery.student_id and ps.parent_profile_id=auth.uid())
);

create policy "attempt_student_insert" on public.question_attempts for insert with check (
  exists (select 1 from public.students s where s.id=question_attempts.student_id and s.profile_id=auth.uid())
);
create policy "attempt_student_read" on public.question_attempts for select using (
  exists (select 1 from public.students s where s.id=question_attempts.student_id and s.profile_id=auth.uid())
);
create policy "attempt_parent_read" on public.question_attempts for select using (
  exists (select 1 from public.parent_students ps where ps.student_id=question_attempts.student_id and ps.parent_profile_id=auth.uid())
);

-- IMPORTANT:
-- Create the first administrator manually AFTER signup:
-- update public.profiles set role='admin' where email='YOUR_ADMIN_EMAIL';
--
-- For MVP parent linking, insert rows manually:
-- insert into public.parent_students(parent_profile_id,student_id) values ('PARENT_PROFILE_UUID','STUDENT_UUID');
