-- SATprep.io production content-bank foundation.
-- Prompts and answer keys are separated so assessment answers never need to ship to the browser.

create table if not exists public.content_items (
  id text primary key,
  version integer not null default 1 check (version > 0),
  content_type text not null check (content_type in ('diagnostic','practice')),
  section text not null check (section in ('RW','MATH')),
  domain_key text not null,
  skill_key text not null,
  difficulty smallint not null check (difficulty between 1 and 3),
  format text not null check (format in ('mcq','spr')),
  stimulus jsonb,
  stem text not null,
  choices jsonb,
  exams text[] not null default array['SAT','PSAT/NMSQT','PSAT 10']::text[],
  estimated_seconds integer check (estimated_seconds between 15 and 600),
  origin text not null default 'satprep_original' check (origin='satprep_original'),
  qa_status text not null default 'draft' check (qa_status in ('draft','internal_review','independent_review','production_approved','retired')),
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_answer_keys (
  item_id text primary key references public.content_items(id) on delete cascade,
  answer jsonb not null,
  explanation text not null,
  distractor_rationales jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.content_item_reviews (
  id bigint generated by default as identity primary key,
  item_id text not null references public.content_items(id) on delete cascade,
  review_type text not null check (review_type in ('accuracy','alignment','editorial','bias_accessibility','originality','psychometric')),
  reviewer_label text,
  decision text not null check (decision in ('approve','revise','reject')),
  content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.diagnostic_attempt_items (
  attempt_id uuid not null references public.diagnostic_attempts(id) on delete cascade,
  position integer not null check (position >= 0),
  item_id text not null references public.content_items(id),
  module smallint not null default 1 check (module in (1,2)),
  is_targeted boolean not null default false,
  selected_at timestamptz not null default now(),
  primary key (attempt_id, position),
  unique (attempt_id, item_id)
);

alter table public.diagnostic_responses add column if not exists content_item_id text references public.content_items(id);
alter table public.diagnostic_responses add column if not exists scored_by_server boolean not null default false;

create index if not exists content_items_skill_idx on public.content_items(content_type,section,domain_key,skill_key,difficulty) where active;
create index if not exists content_items_qa_idx on public.content_items(content_type,qa_status,active);
create index if not exists content_reviews_item_idx on public.content_item_reviews(item_id,review_type,created_at);
create index if not exists diagnostic_attempt_items_attempt_idx on public.diagnostic_attempt_items(attempt_id,position);

alter table public.content_items enable row level security;
alter table public.content_answer_keys enable row level security;
alter table public.content_item_reviews enable row level security;
alter table public.diagnostic_attempt_items enable row level security;
alter table public.diagnostic_responses enable row level security;

-- Proprietary production content, answer keys, review records, and the complete
-- diagnostic item plan are server-only. The authenticated browser receives only
-- safe question projections through server APIs.
-- Explicit revokes complement RLS so a future broad browser policy cannot turn
-- these tables into an accidental content-export endpoint.
revoke all on table public.content_items from public, anon, authenticated;
revoke all on table public.content_answer_keys from public, anon, authenticated;
revoke all on table public.content_item_reviews from public, anon, authenticated;
revoke all on table public.diagnostic_attempt_items from public, anon, authenticated;

drop policy if exists "diagnostic_plan_student_read" on public.diagnostic_attempt_items;
drop policy if exists "diagnostic_plan_parent_read" on public.diagnostic_attempt_items;

-- Secure-v3 responses are server-only. Legacy attempts still need the browser policies
-- that already exist in the MVP schema so an in-progress legacy diagnostic can finish.
-- RESTRICTIVE means this condition is ANDed with any existing permissive student/parent
-- policies: even a broad old policy cannot expose, modify, forge, or delete secure-v3
-- question responses through the browser. The service role bypasses RLS for scoring.
drop policy if exists "secure_v3_responses_server_only" on public.diagnostic_responses;
create policy "secure_v3_responses_server_only"
on public.diagnostic_responses
as restrictive
for all
to authenticated
using (
  not exists (
    select 1 from public.diagnostic_attempts da
    where da.id=diagnostic_responses.attempt_id
      and coalesce(da.summary->>'engine','legacy')='secure-v3'
  )
)
with check (
  not exists (
    select 1 from public.diagnostic_attempts da
    where da.id=diagnostic_responses.attempt_id
      and coalesce(da.summary->>'engine','legacy')='secure-v3'
  )
);

comment on table public.content_items is 'SATprep.io proprietary diagnostic/practice prompts and metadata. Browser roles are denied; safe question delivery is server-mediated.';
comment on table public.content_answer_keys is 'Server-only scoring keys and instructional explanations. Do not expose through browser RLS.';
comment on table public.content_item_reviews is 'Server-only item QA audit trail. Every review is pinned to the SHA-256 hash of the exact prompt, key, explanation, taxonomy, difficulty, exam eligibility, and content type reviewed; originality is required for production diagnostic/practice content.';
comment on table public.diagnostic_attempt_items is 'Server-only immutable-per-attempt diagnostic plan used to verify question order and provenance.';
