-- SATprep.io production content-bank foundation.
-- Prompts and answer keys are separated so diagnostic answers never need to ship to the browser.

create table if not exists public.content_items (
  id text primary key,
  version integer not null default 1 check (version > 0),
  section text not null check (section in ('RW','MATH')),
  domain_key text not null,
  skill_key text not null,
  difficulty smallint not null check (difficulty between 1 and 3),
  format text not null check (format in ('mcq','spr')),
  stimulus jsonb,
  stem text not null,
  choices jsonb,
  exams text[] not null default array['SAT','PSAT/NMSQT','PSAT 10']::text[],
  estimated_seconds integer check (estimated_seconds between 15 and 600),
  origin text not null default 'satprep_original' check (origin='satprep_original'),
  qa_status text not null default 'draft' check (qa_status in ('draft','internal_review','independent_review','production_approved','retired')),
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_answer_keys (
  item_id text primary key references public.content_items(id) on delete cascade,
  answer jsonb not null,
  explanation text not null,
  distractor_rationales jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.content_item_reviews (
  id bigint generated by default as identity primary key,
  item_id text not null references public.content_items(id) on delete cascade,
  review_type text not null check (review_type in ('accuracy','alignment','editorial','bias_accessibility','psychometric')),
  reviewer_label text,
  decision text not null check (decision in ('approve','revise','reject')),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.diagnostic_attempt_items (
  attempt_id uuid not null references public.diagnostic_attempts(id) on delete cascade,
  position integer not null check (position >= 0),
  item_id text not null references public.content_items(id),
  module smallint not null default 1 check (module in (1,2)),
  is_targeted boolean not null default false,
  selected_at timestamptz not null default now(),
  primary key (attempt_id, position),
  unique (attempt_id, item_id)
);

alter table public.diagnostic_responses add column if not exists content_item_id text references public.content_items(id);
alter table public.diagnostic_responses add column if not exists scored_by_server boolean not null default false;

create index if not exists content_items_skill_idx on public.content_items(section,domain_key,skill_key,difficulty) where active;
create index if not exists content_items_qa_idx on public.content_items(qa_status,active);
create index if not exists content_reviews_item_idx on public.content_item_reviews(item_id,review_type);
create index if not exists diagnostic_attempt_items_attempt_idx on public.diagnostic_attempt_items(attempt_id,position);

alter table public.content_items enable row level security;
alter table public.content_answer_keys enable row level security;
alter table public.content_item_reviews enable row level security;
alter table public.diagnostic_attempt_items enable row level security;
alter table public.diagnostic_responses enable row level security;

-- Deliberately no browser SELECT policy on content_items or answer keys.
-- Production question delivery/scoring must go through authenticated server endpoints.
-- This reduces answer-key leakage and makes it harder to scrape the proprietary bank.

create policy "diagnostic_plan_student_read" on public.diagnostic_attempt_items
for select using (
  exists (
    select 1 from public.diagnostic_attempts da
    join public.students s on s.id=da.student_id
    where da.id=diagnostic_attempt_items.attempt_id
      and s.profile_id=auth.uid()
  )
);

create policy "diagnostic_plan_parent_read" on public.diagnostic_attempt_items
for select using (
  exists (
    select 1 from public.diagnostic_attempts da
    join public.parent_students ps on ps.student_id=da.student_id
    where da.id=diagnostic_attempt_items.attempt_id
      and ps.parent_profile_id=auth.uid()
  )
);

-- Secure-v3 responses are server-only. Legacy attempts still need the browser policies
-- that already exist in the MVP schema so an in-progress legacy diagnostic can finish.
-- RESTRICTIVE means this condition is ANDed with any existing permissive student/parent
-- policies: even a broad old policy cannot expose, modify, forge, or delete secure-v3
-- question responses through the browser. The service role bypasses RLS for scoring.
drop policy if exists "secure_v3_responses_server_only" on public.diagnostic_responses;
create policy "secure_v3_responses_server_only"
on public.diagnostic_responses
as restrictive
for all
to authenticated
using (
  not exists (
    select 1 from public.diagnostic_attempts da
    where da.id=diagnostic_responses.attempt_id
      and coalesce(da.summary->>'engine','legacy')='secure-v3'
  )
)
with check (
  not exists (
    select 1 from public.diagnostic_attempts da
    where da.id=diagnostic_responses.attempt_id
      and coalesce(da.summary->>'engine','legacy')='secure-v3'
  )
);

comment on table public.content_items is 'SATprep.io proprietary item prompts and metadata. Answer keys are stored separately and are server-only.';
comment on table public.content_answer_keys is 'Server-only scoring keys and instructional explanations. Do not expose through browser RLS.';
comment on table public.content_item_reviews is 'Item QA audit trail. Production approval requires independent review before public launch.';
