-- SATprep.io first-party marketing measurement foundation.
-- Deliberately excludes user IDs, emails, names, DOB/age, school data, test scores,
-- diagnostic data, uploaded-report data, IP addresses, and persistent browser identifiers.

create table if not exists public.marketing_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_name text not null check (event_name in (
    'marketing_page_view','marketing_cta_click','pricing_view','signup_open','login_open'
  )),
  page_path text not null check (char_length(page_path) between 1 and 240),
  referrer_host text check (referrer_host is null or char_length(referrer_host) <= 160),
  utm_source text check (utm_source is null or char_length(utm_source) <= 100),
  utm_medium text check (utm_medium is null or char_length(utm_medium) <= 100),
  utm_campaign text check (utm_campaign is null or char_length(utm_campaign) <= 140),
  utm_content text check (utm_content is null or char_length(utm_content) <= 140),
  utm_term text check (utm_term is null or char_length(utm_term) <= 140),
  cta_key text check (cta_key is null or char_length(cta_key) <= 80),
  section_key text check (section_key is null or char_length(section_key) <= 80)
);

create index if not exists marketing_events_time_idx on public.marketing_events(occurred_at desc);
create index if not exists marketing_events_campaign_idx on public.marketing_events(utm_campaign, event_name, occurred_at desc);
create index if not exists marketing_events_page_idx on public.marketing_events(page_path, event_name, occurred_at desc);

alter table public.marketing_events enable row level security;

-- No browser policies are intentionally created. Events are accepted only by the
-- same-origin server endpoint using the service role. Public browsers cannot query
-- the event table directly.

comment on table public.marketing_events is 'Privacy-minimized aggregate public-site marketing events. Never store learner or child performance data here.';
