import {QUESTION_BANK,questionById} from '../question-bank.js';
import {buildDiagnosticPlan} from '../diagnostic-blueprint.js';
import {SKILL_INDEX} from '../sat-spec.js';
import {service} from './supabase-server.js';

const LEGACY_TO_OFFICIAL={
 'Analysis':'inferences','Inference':'inferences','Reading Comprehension':'central-ideas-details','Evidence':'command-evidence-textual','Precision':'words-in-context','Vocabulary':'words-in-context','Words in Context':'words-in-context','Organization':'rhetorical-synthesis','Purpose':'rhetorical-synthesis','Style':'rhetorical-synthesis','Rhetorical Synthesis':'rhetorical-synthesis','Writing Mechanics':'form-structure-sense','Grammar':'form-structure-sense','Punctuation':'boundaries','Transitions':'transitions','Linear Equations':'linear-equations-one-variable','Systems':'systems-linear-equations','Functions':'linear-functions','Quadratics':'nonlinear-equations-one-variable','Percent':'percentages','Rates':'ratios-rates-units','Ratios':'ratios-rates-units','Data Analysis':'one-variable-data','Problem Solving':'ratios-rates-units','Geometry':'lines-angles-triangles','Fractions & Decimals':'ratios-rates-units','Number Sense':'ratios-rates-units'
};
function officialSkill(value){const s=String(value||'');return SKILL_INDEX[s]?s:(LEGACY_TO_OFFICIAL[s]||null)}
export function studentPriorities(student){const path=student?.recommended_path||{},raw=path.external_priority_skills||path.priority_skills||[];return raw.map(x=>({skill:officialSkill(x.skill||x.source_skill),mastery:Number(x.mastery??1)})).filter(x=>x.skill).sort((a,b)=>a.mastery-b.mastery)}
function isSecurePlan(ids){return Array.isArray(ids)&&ids.length>0&&ids.every(id=>!!questionById(id))}
export async function latestOpenAttempt(studentId){const rows=await service(`/rest/v1/diagnostic_attempts?student_id=eq.${encodeURIComponent(studentId)}&status=neq.completed&select=id,status,started_at,summary&order=started_at.desc&limit=1`);return rows?.[0]||null}
export async function responseCount(attemptId){const rows=await service(`/rest/v1/diagnostic_responses?attempt_id=eq.${encodeURIComponent(attemptId)}&select=question_key`);return rows?.length||0}
export async function ensureSecureAttempt(student){
 const existing=await latestOpenAttempt(student.id);
 if(existing){const ids=existing.summary?.question_plan||[];return{attempt:existing,legacy:!isSecurePlan(ids),total:ids.length,completed:await responseCount(existing.id)}}
 if(student.diagnostic_completed_at)return{completedDiagnostic:true};
 const priorities=studentPriorities(student),seed=`${student.id}:${new Date().toISOString().slice(0,10)}`,plan=buildDiagnosticPlan({targetExam:student.target_exam||'SAT',priorities,seed}),ids=plan.map(x=>x.itemId),summary={engine:'secure-v3',adaptive:true,assessment_only:true,question_plan:ids,blueprint:plan,external_priorities:priorities,content_version:'bank-v1'};
 const rows=await service('/rest/v1/diagnostic_attempts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({student_id:student.id,status:'in_progress',summary})});
 const attempt=rows?.[0];if(!attempt)throw new Error('Diagnostic attempt could not be created.');return{attempt,legacy:false,total:ids.length,completed:0};
}
export async function ownedAttempt(studentId,attemptId){const rows=await service(`/rest/v1/diagnostic_attempts?id=eq.${encodeURIComponent(attemptId)}&student_id=eq.${encodeURIComponent(studentId)}&select=id,status,started_at,summary`);return rows?.[0]||null}
export function safeQuestion(item,position,total){return{id:item.id,position,total,section:item.section,domain:item.domain,skill:item.skill,difficulty:item.difficulty,format:item.format,stimulus:item.stimulus||null,stem:item.stem,choices:item.choices||null,estimatedSeconds:item.estimatedSeconds}}
export async function questionForAttempt(studentId,attemptId,position){const attempt=await ownedAttempt(studentId,attemptId);if(!attempt)throw Object.assign(new Error('Diagnostic attempt not found.'),{status:404});const ids=attempt.summary?.question_plan||[];if(!isSecurePlan(ids))throw Object.assign(new Error('This diagnostic uses the legacy assessment engine.'),{status:409});const p=Number(position);if(!Number.isInteger(p)||p<0||p>=ids.length)throw Object.assign(new Error('Question position is invalid.'),{status:400});const item=questionById(ids[p]);return{attempt,item,question:safeQuestion(item,p,ids.length)} }
async function existingResponse(attemptId,itemId){const rows=await service(`/rest/v1/diagnostic_responses?attempt_id=eq.${encodeURIComponent(attemptId)}&question_key=eq.${encodeURIComponent(itemId)}&select=question_key,is_correct&limit=1`);return rows?.[0]||null}
export async function scoreDiagnosticAnswer(student,attemptId,position,selectedAnswer,responseMs){const{attempt,item}=await questionForAttempt(student.id,attemptId,position);if(attempt.status==='completed')return{ok:true,completed:true};const selected=Number(selectedAnswer);if(!Number.isInteger(selected)||selected<0||selected>3)throw Object.assign(new Error('Selected answer is invalid.'),{status:400});const prior=await existingResponse(attemptId,item.id);if(!prior){const isCorrect=selected===item.answerIndex;await service('/rest/v1/diagnostic_responses',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({attempt_id:attemptId,student_id:student.id,question_key:item.id,domain:item.domain,skill_key:item.skill,difficulty:item.difficulty,selected_answer:selected,correct_answer:item.answerIndex,is_correct:isCorrect,response_ms:Math.max(0,Math.min(3600000,Number(responseMs)||0))})})}
 const total=attempt.summary.question_plan.length,count=await responseCount(attemptId),completed=count>=total;if(completed)await finalizeSecureDiagnostic(student,attempt);return{ok:true,completed,nextPosition:completed?null:Math.min(total-1,Number(position)+1),answered:count,total}}
async function finalizeSecureDiagnostic(student,attempt){const rows=await service(`/rest/v1/diagnostic_responses?attempt_id=eq.${encodeURIComponent(attempt.id)}&select=question_key,skill_key,is_correct`),ids=attempt.summary?.question_plan||[],allowed=new Set(ids),responses=(rows||[]).filter(r=>allowed.has(r.question_key));if(responses.length<ids.length)return false;const bySkill={},section={RW:{right:0,total:0},MATH:{right:0,total:0}};for(const r of responses){const item=questionById(r.question_key);if(!item)continue;section[item.section].total++;if(r.is_correct)section[item.section].right++;bySkill[r.skill_key]??={right:0,total:0,domain:item.domain,section:item.section};bySkill[r.skill_key].total++;if(r.is_correct)bySkill[r.skill_key].right++}
 const frac=x=>x.total?x.right/x.total:0,mathScore=frac(section.MATH),rwScore=frac(section.RW),overall=(mathScore+rwScore)/2,ranked=Object.entries(bySkill).map(([skill,v])=>({skill,domain:v.domain,section:v.section,mastery:v.right/v.total,items:v.total})).sort((a,b)=>a.mastery-b.mastery),now=new Date().toISOString(),diag={...attempt.summary,priority_skills:ranked.slice(0,8),strengths:[...ranked].sort((a,b)=>b.mastery-a.mastery).slice(0,5),diagnostic_version:'secure-v3',completed_at:now},recommended=overall>=.8?'Accelerated SAT/PSAT Path':overall>=.55?'Core SAT/PSAT Path':'Foundation-Building Path';
 await service(`/rest/v1/diagnostic_attempts?id=eq.${encodeURIComponent(attempt.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'completed',completed_at:now,math_score:mathScore,rw_score:rwScore,overall_score:overall,recommended_start:recommended,summary:diag})});
 const current=student.recommended_path&&typeof student.recommended_path==='object'?student.recommended_path:{},merged={...current,diagnostic:diag,diagnostic_priority_skills:diag.priority_skills,diagnostic_strengths:diag.strengths,diagnostic_completed_at:now};await service(`/rest/v1/students?id=eq.${encodeURIComponent(student.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({diagnostic_completed_at:now,diagnostic_math_mastery:mathScore,diagnostic_rw_mastery:rwScore,recommended_path:merged,onboarding_complete:true})});
 for(const x of ranked)await service('/rest/v1/skill_mastery?on_conflict=student_id,skill_key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({student_id:student.id,skill_key:x.skill,mastery:x.mastery,items_attempted:x.items,updated_at:now})});return true}
export function bankMetadata(){return{items:QUESTION_BANK.length,productionApproved:QUESTION_BANK.filter(x=>x.status==='production_approved').length,internalReview:QUESTION_BANK.filter(x=>x.status==='internal_review').length}}
