import {createHash,randomInt} from 'node:crypto';
import {SKILL_INDEX,skillEligibleForExam,examKey} from '../sat-spec.js';
import {adaptiveBand,selectAdaptiveItems} from '../practice-selection-core.js';
import {COMMERCIAL_CONTENT_POLICY,evaluateSkillCoverage} from '../commercial-content-policy.js';
import {databaseReviewContent} from '../content-integrity.js';
import {answerSpec,scoreResponse} from './response-scoring.js';
import {service} from './supabase-server.js';

const REQUIRED_REVIEWS=['accuracy','alignment','editorial','bias_accessibility','originality'];
const DEFAULT_LENGTH=COMMERCIAL_CONTENT_POLICY.practice.sessionLength;
let readyCache=null;

function examLabel(value){const k=examKey(value);return k==='SAT'?'SAT':k==='PSAT_10'?'PSAT 10':'PSAT/NMSQT'}
function normalize(row){return{id:row.id,section:row.section,domain:row.domain_key,skill:row.skill_key,difficulty:Number(row.difficulty),format:row.format||'mcq',stimulus:row.stimulus??null,stem:row.stem,choices:Array.isArray(row.choices)?row.choices:null,exams:Array.isArray(row.exams)?row.exams:[],estimatedSeconds:Number(row.estimated_seconds)||null}}
function contentHash(row,key){const explanation=typeof key?.explanation==='string'?key.explanation:null,spec=answerSpec(row.format||'mcq',key?.answer);if(!spec||!explanation)return null;const canonical=databaseReviewContent('practice',row,key);return createHash('sha256').update(JSON.stringify(canonical)).digest('hex')}
function latestReviews(rows){const map=new Map();for(const r of rows||[]){if(!r.item_id||!REQUIRED_REVIEWS.includes(r.review_type))continue;const byType=map.get(r.item_id)||new Map();byType.set(r.review_type,r);map.set(r.item_id,byType)}return map}
function approved(reviewMap,itemId,hash){return !!hash&&REQUIRED_REVIEWS.every(type=>{const r=reviewMap.get(itemId)?.get(type);return r?.decision==='approve'&&!!String(r.reviewer_label||'').trim()&&r.content_hash===hash})}
function usableFormat(row){return row?.format==='mcq'||(row?.format==='spr'&&row?.section==='MATH')}

async function practiceSystemReady(){if(readyCache!==null)return readyCache;try{await service('/rest/v1/content_items?select=id,content_type,qa_status,active,format&limit=1');await service('/rest/v1/content_answer_keys?select=item_id,answer,explanation&limit=1');await service('/rest/v1/content_item_reviews?select=item_id,review_type,decision,content_hash&limit=1');await service('/rest/v1/practice_sessions?select=id,score,mastery_after,mastery_before,adaptive_band&limit=1');await service('/rest/v1/practice_session_items?select=session_id,item_id&limit=1');await service('/rest/v1/practice_responses?select=session_id,item_id,selected_answer,response_text,scored_by_server&limit=1');readyCache=true}catch(e){if(e.status===400||e.status===404){readyCache=false;return false}throw e}return readyCache}

async function approvedBank(targetExam,skill){const exam=examLabel(targetExam),encodedSkill=encodeURIComponent(skill);const [items,keys,reviews]=await Promise.all([service(`/rest/v1/content_items?content_type=eq.practice&skill_key=eq.${encodedSkill}&qa_status=eq.production_approved&active=eq.true&select=id,content_type,section,domain_key,skill_key,difficulty,format,stimulus,stem,choices,exams,estimated_seconds&order=id.asc`),service('/rest/v1/content_answer_keys?select=item_id,answer,explanation'),service('/rest/v1/content_item_reviews?select=id,item_id,review_type,reviewer_label,decision,content_hash,created_at&order=created_at.asc,id.asc')]),keyMap=new Map((keys||[]).map(x=>[x.item_id,x])),reviewMap=latestReviews(reviews);return (items||[]).filter(row=>{const key=keyMap.get(row.id),hash=contentHash(row,key);return row.content_type==='practice'&&row.skill_key===skill&&usableFormat(row)&&Array.isArray(row.exams)&&row.exams.includes(exam)&&approved(reviewMap,row.id,hash)}).map(normalize)}

async function approvedContent(itemId){const encoded=encodeURIComponent(itemId),[items,keys,reviews]=await Promise.all([service(`/rest/v1/content_items?id=eq.${encoded}&content_type=eq.practice&qa_status=eq.production_approved&active=eq.true&select=id,content_type,section,domain_key,skill_key,difficulty,format,stimulus,stem,choices,exams,estimated_seconds&limit=1`),service(`/rest/v1/content_answer_keys?item_id=eq.${encoded}&select=item_id,answer,explanation&limit=1`),service(`/rest/v1/content_item_reviews?item_id=eq.${encoded}&select=id,item_id,review_type,reviewer_label,decision,content_hash,created_at&order=created_at.asc,id.asc`)]),row=items?.[0],key=keys?.[0];if(!row||row.content_type!=='practice'||!key||!usableFormat(row))throw Object.assign(new Error('This practice item is not currently approved for use.'),{status:503});const hash=contentHash(row,key),reviewMap=latestReviews(reviews);if(!approved(reviewMap,itemId,hash))throw Object.assign(new Error('This practice item changed after review or is not currently approved for use.'),{status:503});if(!answerSpec(row.format||'mcq',key.answer)||typeof key.explanation!=='string')throw Object.assign(new Error('The approved practice scoring material is not ready.'),{status:503});return{item:normalize(row),answer:key.answer,explanation:key.explanation,contentHash:hash}}

async function latestOpen(studentId,skill){const rows=await service(`/rest/v1/practice_sessions?student_id=eq.${encodeURIComponent(studentId)}&skill_key=eq.${encodeURIComponent(skill)}&status=eq.in_progress&select=id,student_id,skill_key,target_exam,status,mastery_before,adaptive_band,score,mastery_after,started_at,updated_at&order=updated_at.desc&limit=1`);return rows?.[0]||null}
async function ownedSession(studentId,sessionId){const rows=await service(`/rest/v1/practice_sessions?id=eq.${encodeURIComponent(sessionId)}&student_id=eq.${encodeURIComponent(studentId)}&select=id,student_id,skill_key,target_exam,status,mastery_before,adaptive_band,score,mastery_after,started_at,updated_at,completed_at&limit=1`);return rows?.[0]||null}
async function planRows(sessionId){return await service(`/rest/v1/practice_session_items?session_id=eq.${encodeURIComponent(sessionId)}&select=position,item_id&order=position.asc`)||[]}
async function responseRows(sessionId){return await service(`/rest/v1/practice_responses?session_id=eq.${encodeURIComponent(sessionId)}&scored_by_server=eq.true&select=position,item_id,selected_answer,response_text,is_correct,created_at&order=position.asc`)||[]}
async function responseCount(sessionId){return (await responseRows(sessionId)).length}
async function masteryForSkill(studentId,skill){const rows=await service(`/rest/v1/skill_mastery?student_id=eq.${encodeURIComponent(studentId)}&skill_key=eq.${encodeURIComponent(skill)}&select=mastery,items_attempted&limit=1`).catch(()=>[]);const raw=rows?.[0]?.mastery;return raw==null?null:Number(raw)}
function safeQuestion(item,position,total){return{id:item.id,position,total,section:item.section,domain:item.domain,skill:item.skill,difficulty:item.difficulty,format:item.format,stimulus:item.stimulus??null,stem:item.stem,choices:item.format==='mcq'?(item.choices||null):null,estimatedSeconds:item.estimatedSeconds}}

export async function ensurePracticeSession(student,skill,{length=DEFAULT_LENGTH}={}){if(!student?.diagnostic_completed_at)throw Object.assign(new Error('Complete the initial diagnostic before starting guided practice.'),{status:409});const meta=SKILL_INDEX[skill],exam=examLabel(student.target_exam||'SAT');if(!meta||!skillEligibleForExam(skill,exam))throw Object.assign(new Error('This skill is not available for the selected exam.'),{status:400});if(!(await practiceSystemReady()))throw Object.assign(new Error('Commercial practice sessions are not ready yet.'),{status:503});const mastery=await masteryForSkill(student.id,skill),band=adaptiveBand(mastery),existing=await latestOpen(student.id,skill);if(existing){const plan=await planRows(existing.id),bank=await approvedBank(exam,skill),approvedIds=new Set(bank.map(x=>x.id));if(!plan.length||!plan.every(x=>approvedIds.has(x.item_id)))throw Object.assign(new Error('Your saved practice session contains content that is no longer approved. Your progress has not been altered.'),{status:503});const answered=await responseCount(existing.id);return{session:existing,total:plan.length,answered,resumed:true,adaptiveBand:existing.adaptive_band||band}}
 const bank=await approvedBank(exam,skill),coverage=evaluateSkillCoverage(bank,'practice');if(!coverage.ready||bank.length<length)throw Object.assign(new Error(`Commercial practice for this skill requires at least ${Math.max(length,COMMERCIAL_CONTENT_POLICY.practice.minApprovedPerSkill)} independently reviewed items with the approved adaptive difficulty mix.`),{status:503});const recent=await service(`/rest/v1/practice_responses?student_id=eq.${encodeURIComponent(student.id)}&select=item_id&order=created_at.desc&limit=20`).catch(()=>[]),recentIds=new Set((recent||[]).map(x=>x.item_id)),fresh=bank.filter(x=>!recentIds.has(x.id)),source=fresh.length>=length?fresh:bank,sprTarget=meta.section==='MATH'?Math.max(1,Math.round(length*.25)):0,chosen=selectAdaptiveItems(source,{length,mastery,sprTarget,randomIntFn:randomInt});const rows=await service('/rest/v1/practice_sessions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({student_id:student.id,skill_key:skill,target_exam:exam,status:'in_progress',content_version:'server-practice-v5-depth-spr',mastery_before:mastery,adaptive_band:band})}),session=rows?.[0];if(!session)throw new Error('Practice session could not be created.');try{await service('/rest/v1/practice_session_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(chosen.map((q,position)=>({session_id:session.id,position,item_id:q.id})))})}catch(e){await service(`/rest/v1/practice_sessions?id=eq.${encodeURIComponent(session.id)}`,{method:'DELETE'}).catch(()=>{});throw e}return{session,total:chosen.length,answered:0,resumed:false,adaptiveBand:session.adaptive_band||band}}

export async function questionForPractice(studentId,sessionId,position,{enforceCurrent=true}={}){const session=await ownedSession(studentId,sessionId);if(!session)throw Object.assign(new Error('Practice session not found.'),{status:404});if(session.status==='completed')throw Object.assign(new Error('This practice session is already complete.'),{status:409});if(session.status!=='in_progress')throw Object.assign(new Error('This practice session is not active.'),{status:409});const plan=await planRows(sessionId),p=Number(position);if(!Number.isInteger(p)||p<0||p>=plan.length)throw Object.assign(new Error('Practice question position is invalid.'),{status:400});const answered=await responseCount(sessionId);if(enforceCurrent&&p!==answered)throw Object.assign(new Error(`Continue from practice question ${Math.min(answered+1,plan.length)}.`),{status:409});const expected=plan[p];if(expected.position!==p)throw Object.assign(new Error('The saved practice plan could not be verified.'),{status:503});const{item}=await approvedContent(expected.item_id);if(item.skill!==session.skill_key)throw Object.assign(new Error('The saved practice content does not match this skill.'),{status:503});return{session,question:safeQuestion(item,p,plan.length)}}

function feedback(item,scored,explanation){return{correct:scored.correct,format:item.format,selected_answer:scored.selectedAnswer,response_text:scored.responseText,correct_answer_index:scored.correctIndex,correct_answer:item.format==='mcq'?(item.choices?.[scored.correctIndex]??null):scored.correctDisplay,explanation}}
function storedMatches(row,scored){return scored.selectedAnswer!==null?Number(row.selected_answer)===scored.selectedAnswer:String(row.response_text||'')===scored.responseText}
async function finalize(sessionId){const rows=await service('/rest/v1/rpc/finalize_practice_session',{method:'POST',body:JSON.stringify({p_session_id:sessionId})}),r=Array.isArray(rows)?rows[0]:rows;return{completed:!!r?.completed,score:r?.score==null?null:Number(r.score),mastery_after:r?.mastery_after==null?null:Number(r.mastery_after)}}

export async function scorePracticeAnswer(student,sessionId,position,submittedResponse,responseMs){if(!(await practiceSystemReady()))throw Object.assign(new Error('Commercial practice sessions are not ready yet.'),{status:503});const session=await ownedSession(student.id,sessionId);if(!session)throw Object.assign(new Error('Practice session not found.'),{status:404});if(session.status==='completed')return{ok:true,completed:true,score:Number(session.score),mastery_after:Number(session.mastery_after)};if(session.status!=='in_progress')throw Object.assign(new Error('This practice session is not active.'),{status:409});const plan=await planRows(sessionId),p=Number(position);if(!Number.isInteger(p)||p<0||p>=plan.length)throw Object.assign(new Error('Practice question position is invalid.'),{status:400});const expected=plan[p];if(expected.position!==p)throw Object.assign(new Error('The saved practice plan could not be verified.'),{status:503});const{item,answer,explanation}=await approvedContent(expected.item_id);if(item.skill!==session.skill_key)throw Object.assign(new Error('The saved practice content does not match this skill.'),{status:503});const scored=scoreResponse(item.format,answer,submittedResponse);if(!scored.valid)throw Object.assign(new Error(scored.error||'Practice response is invalid.'),{status:scored.keyInvalid?503:400});const existing=(await responseRows(sessionId)).find(x=>x.position===p);if(existing){if(!storedMatches(existing,scored))throw Object.assign(new Error('This practice answer was already submitted and cannot be changed.'),{status:409});const count=await responseCount(sessionId),done=count>=plan.length,result=done?await finalize(sessionId):{completed:false};return{ok:true,...feedback(item,scored,explanation),correct:!!existing.is_correct,answered:count,total:plan.length,next_position:done?null:count,...result,idempotent:true}}
 const answered=await responseCount(sessionId);if(p!==answered)throw Object.assign(new Error(`Continue from practice question ${Math.min(answered+1,plan.length)}.`),{status:409});try{await service('/rest/v1/practice_responses',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({session_id:sessionId,student_id:student.id,item_id:item.id,position:p,selected_answer:scored.selectedAnswer,response_text:scored.responseText,is_correct:scored.correct,response_ms:Math.max(0,Math.min(3600000,Number(responseMs)||0)),scored_by_server:true})})}catch(e){if(e.status!==409)throw e;const raced=(await responseRows(sessionId)).find(x=>x.position===p);if(!raced||!storedMatches(raced,scored))throw e}
 const count=await responseCount(sessionId),done=count>=plan.length;let result={completed:false};if(done)result=await finalize(sessionId);else await service(`/rest/v1/practice_sessions?id=eq.${encodeURIComponent(sessionId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({updated_at:new Date().toISOString()})});return{ok:true,...feedback(item,scored,explanation),answered:count,total:plan.length,next_position:done?null:count,...result}}

export async function practiceState(studentId,sessionId){const session=await ownedSession(studentId,sessionId);if(!session)return null;const plan=await planRows(sessionId),answered=await responseCount(sessionId);return{session_id:session.id,skill_key:session.skill_key,status:session.status,total:plan.length,answered,adaptive_level:session.adaptive_band||null,mastery_before:session.mastery_before==null?null:Number(session.mastery_before),score:session.score==null?null:Number(session.score),mastery_after:session.mastery_after==null?null:Number(session.mastery_after)}}
