import {createHash} from 'node:crypto';

const PUBLIC_APP_HOSTS=new Set(['satprep.io','www.satprep.io']);
function apiConfig(){const url=process.env.VITE_SUPABASE_URL,anon=process.env.VITE_SUPABASE_ANON_KEY,serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!anon||!serviceKey)throw new Error('Server data access is not configured.');return{url,anon,serviceKey}}
function requestHost(req){const raw=String(req?.headers?.['x-forwarded-host']||req?.headers?.host||'').split(',')[0].trim().toLowerCase();return raw.replace(/:\d+$/,'')}
function verifyExplicitOrigin(host,rawOrigin){try{const origin=new URL(rawOrigin),hostname=origin.hostname.toLowerCase(),local=['localhost','127.0.0.1'].includes(hostname);if(origin.protocol!=='https:'&&!(origin.protocol==='http:'&&local))throw new Error('protocol');if(!host||hostname!==host)throw new Error('host')}catch{throw Object.assign(new Error('Request origin could not be verified.'),{status:403})}}
export function assertAppRequestOrigin(req){const host=requestHost(req),rawOrigin=String(req?.headers?.origin||'').trim(),fetchSite=String(req?.headers?.['sec-fetch-site']||'').trim().toLowerCase();if(fetchSite&&!['same-origin','none'].includes(fetchSite))throw Object.assign(new Error('Request must originate from the SATprep.io application.'),{status:403});if(!rawOrigin){if(PUBLIC_APP_HOSTS.has(host))throw Object.assign(new Error('Request origin could not be verified.'),{status:403});return}verifyExplicitOrigin(host,rawOrigin)}
export function assertAppReadOrigin(req){const host=requestHost(req),rawOrigin=String(req?.headers?.origin||'').trim(),fetchSite=String(req?.headers?.['sec-fetch-site']||'').trim().toLowerCase();if(fetchSite&&!['same-origin','none'].includes(fetchSite))throw Object.assign(new Error('Request must originate from the SATprep.io application.'),{status:403});if(rawOrigin){verifyExplicitOrigin(host,rawOrigin);return}if(PUBLIC_APP_HOSTS.has(host)&&fetchSite!=='same-origin')throw Object.assign(new Error('Request origin could not be verified.'),{status:403})}
export function json(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').setHeader('Cache-Control','no-store, max-age=0').setHeader('Pragma','no-cache').setHeader('X-Content-Type-Options','nosniff').setHeader('Referrer-Policy','no-referrer').setHeader('Cross-Origin-Resource-Policy','same-origin').setHeader('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'").setHeader('Vary','Authorization, Origin').send(JSON.stringify(body))}
export async function authenticatedUser(req){const{url,anon}=apiConfig(),auth=String(req.headers.authorization||'');if(!/^Bearer\s+\S+$/i.test(auth))return null;const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:anon,Authorization:auth}});if(!r.ok)return null;const user=await r.json();return{user,auth,url,anon}}
export async function service(path,options={}){const{url,serviceKey}=apiConfig();const r=await fetch(`${url}${path}`,{...options,headers:{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const e=new Error(data?.message||data?.msg||data?.error_description||data?.error||`Database request failed (${r.status})`);e.status=r.status;throw e}return data}
export async function removeStorageObjects(bucket,paths){const safeBucket=String(bucket||'').trim(),prefixes=(Array.isArray(paths)?paths:[]).map(p=>String(p||'').trim()).filter(Boolean);if(!/^[a-z0-9][a-z0-9._-]{0,99}$/i.test(safeBucket)||!prefixes.length||prefixes.length>1000)throw Object.assign(new Error('Invalid storage deletion request.'),{status:400});if(prefixes.some(p=>p.startsWith('/')||p.includes('..')||p.length>1024))throw Object.assign(new Error('Invalid storage object path.'),{status:400});return service(`/storage/v1/object/${encodeURIComponent(safeBucket)}`,{method:'DELETE',body:JSON.stringify({prefixes})})}
export async function enforceRateLimit(subject,route,{limit=60,windowSeconds=60}={}){const rawSubject=String(subject||'').trim(),routeKey=String(route||'').trim().toLowerCase();if(!rawSubject||!routeKey)throw Object.assign(new Error('Rate-limit identity is required.'),{status:500});const keyHash=createHash('sha256').update(`${routeKey}|${rawSubject}`).digest('hex');let result;try{result=await service('/rest/v1/rpc/consume_api_rate_limit',{method:'POST',body:JSON.stringify({p_key_hash:keyHash,p_route_key:routeKey,p_window_seconds:windowSeconds,p_limit:limit})})}catch(err){console.error('rate-limit backend unavailable',routeKey,err);throw Object.assign(new Error('Request protection is not ready.'),{status:503})}const state=Array.isArray(result)?result[0]:result;if(!state||typeof state.allowed!=='boolean')throw Object.assign(new Error('Request protection is not ready.'),{status:503});if(!state.allowed){const reset=Date.parse(state.reset_at||''),retryAfter=Number.isFinite(reset)?Math.max(1,Math.ceil((reset-Date.now())/1000)):windowSeconds;throw Object.assign(new Error('Too many requests. Please wait and try again.'),{status:429,retryAfter})}return state}
export async function studentContext(req){const a=await authenticatedUser(req);if(!a)return null;const profiles=await service(`/rest/v1/profiles?id=eq.${encodeURIComponent(a.user.id)}&select=id,email,role,first_name,household_id,is_test_account`);const profile=profiles?.[0];if(!profile||profile.role!=='student')return{...a,profile,student:null};const students=await service(`/rest/v1/students?profile_id=eq.${encodeURIComponent(profile.id)}&select=id,profile_id,target_exam,target_score,onboarding_complete,diagnostic_completed_at,recommended_path,is_test_student,test_label`);return{...a,profile,student:students?.[0]||null}}
