import crypto from "node:crypto";
export const config={api:{bodyParser:false}};
async function rawBody(req){const chunks=[];for await(const c of req)chunks.push(Buffer.isBuffer(c)?c:Buffer.from(c));return Buffer.concat(chunks).toString("utf8")}
function safeEqual(a,b){try{const aa=Buffer.from(a,"hex"),bb=Buffer.from(b,"hex");return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb)}catch{return false}}
function verify(raw,header,secret){if(!header||!secret)return false;const parts=header.split(",").map(x=>x.split("=")),t=parts.find(x=>x[0]==="t")?.[1],sigs=parts.filter(x=>x[0]==="v1").map(x=>x[1]);if(!t||!sigs.length||Math.abs(Date.now()/1000-Number(t))>300)return false;const expected=crypto.createHmac("sha256",secret).update(`${t}.${raw}`,"utf8").digest("hex");return sigs.some(s=>safeEqual(expected,s))}
function cfg(){return{url:process.env.VITE_SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY}}
function headers(){const{key}=cfg();return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"}}
async function api(path,options={}){const{url,key}=cfg();if(!url)throw new Error("missing VITE_SUPABASE_URL");if(!key)throw new Error("missing SUPABASE_SERVICE_ROLE_KEY");const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{...headers(),...(options.headers||{})}});const text=await r.text();if(!r.ok){const e=new Error(`Supabase ${r.status}: ${text.slice(0,500)}`);e.status=r.status;throw e}return text?JSON.parse(text):null}
async function recordEvent(event){try{await api("stripe_events",{method:"POST",body:JSON.stringify({event_id:event.id,event_type:event.type})});return true}catch(e){if(e.status===409||String(e.message).includes("duplicate key"))return false;throw e}}
async function syncSubscription(s){const meta=s.metadata||{};console.log("stripe-webhook sync",s.id,s.status,{household:!!meta.household_id,billing:!!meta.billing_profile_id,plan:meta.plan_key||null});if(!meta.billing_profile_id||!meta.household_id){console.warn("stripe-webhook subscription missing SATprep metadata",s.id);return}
 const payload={profile_id:meta.billing_profile_id,billing_profile_id:meta.billing_profile_id,household_id:meta.household_id,provider:"stripe",provider_customer_id:typeof s.customer==="string"?s.customer:s.customer?.id||null,provider_subscription_id:s.id,plan_key:meta.plan_key||null,status:s.status||"inactive",trial_ends_at:s.trial_end?new Date(s.trial_end*1000).toISOString():null,current_period_end:s.current_period_end?new Date(s.current_period_end*1000).toISOString():null,cancel_at_period_end:!!s.cancel_at_period_end,updated_at:new Date().toISOString()};
 await api("subscriptions?on_conflict=provider_subscription_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload)});const limit=String(meta.plan_key||"").startsWith("family_")?3:1;await api(`households?id=eq.${encodeURIComponent(meta.household_id)}`,{method:"PATCH",body:JSON.stringify({plan_key:meta.plan_key||null,student_limit:limit})});console.log("stripe-webhook subscription synchronized",s.id)}
export default async function handler(req,res){if(req.method!=="POST")return res.status(405).send("Method not allowed");try{const raw=await rawBody(req);if(!process.env.STRIPE_WEBHOOK_SECRET){console.error("stripe-webhook missing STRIPE_WEBHOOK_SECRET");return res.status(500).send("Webhook secret not configured")}if(!verify(raw,req.headers["stripe-signature"],process.env.STRIPE_WEBHOOK_SECRET)){console.error("stripe-webhook invalid signature");return res.status(400).send("Invalid Stripe signature")}const event=JSON.parse(raw);console.log("stripe-webhook received",event.id,event.type);if(!(await recordEvent(event)))return res.status(200).json({received:true,duplicate:true});if(["customer.subscription.created","customer.subscription.updated","customer.subscription.deleted"].includes(event.type))await syncSubscription(event.data.object);return res.status(200).json({received:true})}catch(e){console.error("stripe-webhook failure",e?.message||e);return res.status(500).json({error:"Webhook processing failed",detail:String(e?.message||e).slice(0,500)})}}
